### ISSUE TITLE
C1083 无法打开包括文件: “SDL.h”: No such file or directory

### ISSUE THREAD

**Issue by wuyizhan520** [sdlpal/sdlpal#102]
我把代码clone下来以后，在vs2015中打开，F5运行的时候提示题目说的这个错误，请问是哪里的问题呀？缺少SDL.h这个文件吗？

**Comment by PalMusicFan** [comment]
您好，clone之后您是否做过以下操作？
cd sdlpal
git submodule update --init --recursive

**Comment by wuyizhan520** [comment]
您好，git submodule update --init --recursive 这样操作完以后在vs2015解决方案资源管理器里面SDL2显示加载失败，F5以后还是之前那个错误：C1083 无法打开包括文件: “SDL.h”: No such file or directory，请问是哪里的问题呢？

**Comment by PalMusicFan** [comment]
请检查您的网络。假如总是出错，请更换网络线路。

**Comment by wuyizhan520** [comment]
您好，git submodule update --init --recursive，执行失败，确实是网络的问题，我早上又试了一遍现在已经可以run成功了，在弹出的对话框有个“启动游戏”的按钮，我点击以后又报了一个错误，File open error[2]:fbp.mkf!，百度以后发现，应该是缺少fbp.mkf资源文件，请问clone下来的文件包含这个资源文件吗，这个问题该如何解决呢？谢谢

**Comment by zephray** [comment]
fbp.mkf是原版仙剑奇侠传的资源文件之一，因为版权原因，sdlpal项目是不分发这些内容的。可以自行下载原版的仙剑奇侠传（DOS版、95版或者98版），复制其中的资源文件补齐。
