### ISSUE TITLE
wingw 编译错误

### ISSUE THREAD

**Issue by kli2013** [sdlpal/sdlpal#104]
C:\mingw\bin>make -f "F:\Temp\sdlpal-master\win32\Makefile.mingw"
[LD] sdlpal-mingw.exe
C:/mingw/bin/../lib/gcc/mingw32/5.1.0/../../../../mingw32/bin/ld.exe: cannot find -lSDL2main
C:/mingw/bin/../lib/gcc/mingw32/5.1.0/../../../../mingw32/bin/ld.exe: cannot find -lSDL2
collect2.exe: error: ld returned 1 exit status
F:\Temp\sdlpal-master\win32\Makefile.mingw:38: recipe for target 'sdlpal-mingw.exe' failed
mingw32-make: *** [sdlpal-mingw.exe] Error 1

**Comment by palxex** [comment]
Your MinGW distribution does not contains SDL2, or its SDL2 library not in your path.
Build SDL2 yourself or obtain a new distribution that contains it, like https://nuwen.net/mingw.html
