### ISSUE TITLE
编译错误--linux

### ISSUE THREAD

**Issue by yangxuanx** [sdlpal/sdlpal#105]
![image](https://user-images.githubusercontent.com/26968633/44183090-368b2b00-a13c-11e8-83fb-2a8ae0a38dfc.png)

**Comment by yangxuanx** [comment]
ubuntu18.04

**Comment by zephray** [comment]
Please make sure you have libsdl2-dev installed.

**Comment by yangxuanx** [comment]
感谢您的回复！确实缺失libsdl2-dev，之前安装成libsdl-dev。现在编译正常了，启动后现游戏配置界面，点击确定出现错误，错误提示如下
![image](https://user-images.githubusercontent.com/26968633/44183801-098c4780-a13f-11e8-8605-d036911946ac.png)

**Comment by zephray** [comment]
> When it complains fbp.mkf, mostly resource not available. SDLPal is a engine-only clean-room remake. For copyright reason data files required to run the game are NOT included.
> The game can be downloaded for free legally at the official website of Baiyou:
http://update1.baiyou100.com/resource/Pal98rqp.zip
Basically you need to download the original game and unzip it to somewhere, and set the resource directory accordingly in the game configuration.

**Comment by yangxuanx** [comment]
非常感谢，可以玩了，哈哈
