### ISSUE TITLE
【Bug】我方被定身时不显示“定”字

### ISSUE THREAD

**Issue by liuzhun007** [sdlpal/sdlpal#109]
以下两种情况下，我方被定身，但并不显示“定”字：
1）我方服用醍醐香；
2）修改游戏设置敌方普攻自带捆仙绳/醍醐香使我方被定身。
原版pal.exe会显示“定”字以供玩家辨认状态。

**Comment by palxex** [comment]
Thanks for reporting, confirmed and will fix in later commit.
