### ISSUE TITLE
畫面變成黃色，按下home鍵回桌面的時候才會看到正常色彩

### ISSUE THREAD

**Issue by CecilHarvey** [sdlpal/sdlpal#113]
from: | 菲尼 <xxxx@gmail.com>
to: | whistler_wmz@users.sf.net
date: | Oct 25, 2018, 12:52 PM
subject: | 你好，PAL我遇到了一個問題

如題，我下載了你的仙劍啟動器，手機是華碩的zenfone 5z，安卓版本是8.0，仙劍dos跟95版都正常運行，不過畫面變成黃色，按下home鍵回桌面的時候才會看到正常色彩，不知有無解決方法？

**Comment by palxex** [comment]
一加一安卓8没有这个问题，应该跟系统版本无关。最好请用户截图看一下具体情况。

**Comment by Phoenix1222** [comment]
情況是這樣
https://i.imgur.com/ssZhMbz.jpg

**Comment by palxex** [comment]
。。。这个真没见过。像是开了某种滤镜，但从手柄图标的情况看跟游戏内滤镜系统的表现无关（另外如果你是从google play下的话应该还没有这个选项）。回想下是否在华硕的游戏中心里开过什么效果器之类的？

**Comment by PalMusicFan** [comment]
奇怪问题啊。建议下载最新的nighty build版安装（如果之前安装了Play版，请先卸载），然后启用GLSL滤镜，加载plain.glsl空滤镜（ https://github.com/sdlpal/sdlpal/raw/master/shaders/plain.glsl ），看看是什么效果。

**Comment by palxex** [comment]
Closing due to lack of discuss, let's reopen it once needed.
