### ISSUE TITLE
mac 版的遊戲畫面為什麼強行變成了 4:3？

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#114]
我記得遊戲原本的素材與畫面表現正好可以填滿 1280x800 不留黑邊的。

**Comment by ShikiSuen** [comment]
发现可以写 cfg 绕开这个设定。
於是，这个 issue 就是建议将预设参数改成 960x600。
```
WindowHeight=600
WindowWidth=960
TextureHeight=600
TextureWidth=960
```
这套参数是照顾到了很多装载 1366x768 萤幕的笔电，不然直接 1280x800 即可。

**Comment by ShikiSuen** [comment]
而且，上一条回覆建议的萤幕尺寸正好就是对游戏原始萤幕尺寸比率（320x200）的倍数放大，正好可以还原游戏本来设计时的尺寸。

**Comment by palxex** [comment]
不太清楚你碰到的什么问题。我来解释下分辨率相关设置的设计和考虑。
最开始SDLPal只有WindowWidth/Height，作为初始窗口分辨率；窗口可随意拉伸，拉伸后填充到满窗口；全屏下使用SDL的全屏化窗口进行全屏拉伸。这样在切换全屏/拉伸时，人物比例可能会各种变化。
为了能在切换/拉伸时保持纵横比，KeepAspectRatio被引入并默认开。最初这个设计只能保持16:10，也就是仙剑资源里像素等比的纵横比。后来因为得知早期游戏设计上像素未必是正方形（http://daily.zhihu.com/story/7914842 提到的就有Super Mario和Street Fighter），因此模拟器多有矫正措施（比如dosbox的aspect），而且个人观感上CRT时代常用的4:3下的人物头像更适合原版的美术设计（纯属个人观感，没有向原设计人员求证，但即使原设不是，用户也应该有自行指定的权力），为此又引入了能手动指定纵横比的设置，经过多次演化后当前稳定在TextureWidth/Height形成的比例上（做这么复杂是因为GLSL滤镜需要用这组设置的实际大小做FBO，影响性能——非滤镜模式则只有其比例被用到）。是的，TextureSize的比例可以与WindowSize不同；这种情况下会视配置出现上下或左右黑边，所以习惯上还是设成一致的更好，但全屏下因为窗口大小设置失效还是可能出黑边。
说完了机制，接下来看默认设置。你可以用一个空的sdlpal.cfg启动游戏看看，用游戏内菜单正常退出游戏后自动保存的相关配置应该是
```
KeepAspectRatio=1
WindowHeight=400
WindowWidth=640
TextureHeight=400
TextureWidth=640
```
这套默认设置的结果其实就是16:10，在1280x800下全屏不应有黑边。如果你用空配置启动/保存的结果与此不同，请post到这里。另外请确保用当前master代码编译运行。

**Comment by palxex** [comment]
4:3是否理想尺寸其实无关紧要吧，在用户可以自行定义的情况下。这只是我个人因为历史因素认为的理想比例，并不强求他人认同，也未设置为默认选项（如果你发现没有自行配置过——可以理解为没有sdlpal.cfg——的*干净启动*会出现这个比例——这是**未预期的**，可以认为是bug，请描述一下具体情况包括OS/编译器版本/etc以便测试修复）。至于默认，考虑到作为重制，像素级精确是起码的要求，以原图可以**精确**输出的16:10为默认是最优选项，某种意义上这也是出于最小惊奇原则的考虑。至于是320x200，640x400还是960x600，窃以为留给知道自己在做什么的高级用户根据实际情况自定即可。有修改需要的完全可以自己编译后带上配置文件一起分发。

**Comment by palxex** [comment]
因为我本地(mojave正式版，xcode 10A255)尝试干净启动时并没有问题——正确出现了16:10的游戏窗口。暂时认为没有问题，有不同的发现请提交并reopen。

**Comment by ShikiSuen** [comment]
@palxex 想必是 Release 发行包里面内建的 cfg 所致。
