### ISSUE TITLE
[request] gradle build system support for android

### ISSUE THREAD

**Issue by palxex** [sdlpal/sdlpal#12]
Seems ant scripts has been removed in latest Android SDK tools for macOS, which is the current build system for SDLPal Android. Not sure whether it will happen to windows/linux version in future. Does anyone familiar with migration from ant to gradle build system?

**Comment by louyihua** [comment]
Seems we don't have much customizations in the ant build.xml, so maybe it is quite straightforward to migrate to gradle?

**Comment by palxex** [comment]
Merged PR https://github.com/sdlpal/sdlpal/pull/14, close the issue.
