### ISSUE TITLE
建议android studio build的说明文档更加详细一些

### ISSUE THREAD

**Issue by ny83427** [sdlpal/sdlpal#120]
按照readme.md中的说明，我可以通过visual studio 2017编译windows版本，并在下载资源文件之后，成功运行并调试。

但是android版本，目前仅有的说明只有“To build the game, open the android directory through Android Studio, and click Make Project.”，按照这个提示，下载最新的android studio，发现要填的坑是一坨一坨...

期望与建议：能否将android部分的build说明，写得稍微详细一些，并针对一些可能的版本更新问题，作出一些同步？

PS：我对android了解不多，但是对这游戏很有感情，所以也是想通过跑这游戏顺便来玩玩android。小白一只，求轻拍。

**Comment by palxex** [comment]
请自行总结一下填过的坑，发上来开发者会审阅是否适合加入文档。
个人经验是配置好android studio就能打开sdlpal编译了（可能第一次要等很久——等gradle编译完成），没碰过什么问题。要我来设想可能存在的问题的话，最大的可能是不熟悉android studio（安装SDK什么的），这部分写入sdlpal的文档并不合适。另一部分可能是网络问题，那就更不合适了。
对非NDK开发者，最简单的编译安装步骤是进android目录后gradlew installDebug。连下载SDK都会代劳。

**Comment by palxex** [comment]
因无有效反馈关闭。
