### ISSUE TITLE
[Feature request] update translation spec to avoid further misinterpretion

### ISSUE THREAD

**Issue by palxex** [sdlpal/sdlpal#121]
**Is your feature request related to a problem? Please describe.**
SDLPal have escape characters. Which makes English translation sometimes enter displaying problem like the screenshot above.
![2018-11-18 9 41 12](https://user-images.githubusercontent.com/58222/48673277-c517aa00-eb7a-11e8-86af-f3ae5959a0b3.png)

**Describe the solution you'd like**
What I can imagine is either: disable escape characters for specified translation ( for ex. via a new option ), at least for those which commonly used in English;

**Describe alternatives you've considered**
Or: enable an unescape system, and replace all apostrophe ( like ' ) with their unescaped form ( like \\' ) in translation file.
Welcome for new suggestions that less invasive.

**Additional context**
Complete scape character list until [now]( ../commit/204db62 )( see [TEXT_DisplayText](../blob/master/text.c#L1324) ):

charactor | representation | meaning
------------ | ------------- | -------------
minus | -  | turn latter font color to cyan, until another minus
apostrophe | ' | turn latter font color to red, until another apostrophe
at | @ | turn latter font color to lighter red, until another at
double quote | " |  turn latter font color to yellow, until another double quote
dollar | $ | set the delay time of text-displaying
tilde | ~ | delay for a period and quit
parentheses | () | set the waiting icon( two form )
backslash | \\ | do NOTHING( not even display )

Regression:
In fact this is not a new conflicting. It just newly appeared. The very beginning game design uses those ASCII characters for special usage, since it is a Chinese game, these character should NEVER appears in game content. BUT now SDLPal already have i18n support, and English l10n text, then the assumption is already not correct. The apostrophe was introduced in b9bda6a, which intends for fixing text color changing which required in a famous OLD MOD( released in around 2006 ) "paldream 2.11". Without the patchset, in some scene the mod will not works as intended( which involves Chinese acrostic poem art ), but with it the ( current ) English translation enters problem like the screenshot suggests. That's why we need a new solution.

**Comment by Nostaljaded** [comment]
**Support the 'enable an unescape system'**
Have the 'unescape' symbol added in the message.py export for those special characters.

Translations would remain as plain translation work while still able to display the original, intended font styling (in whatever languages) to the players.

Need to have a 'case selection' code in SDLPAL to:

- enable 'unescape system' if 'MessageFileName' in sdlpal.cfg uses an external message file
- disable 'unescape system' if using 'm.msg'

**Comment by Nostaljaded** [comment]
So I guessed it's a combination of the solution & alternative you have proposed. :)

- a new option in message spec to enable/disable 'the unescape system', according to the language translator's preference
- message.py export to have a 'switch' to enable/disable the addition of 'unescape' symbol (default option / without specifying the 'switch' should set as 'disable')

**Comment by palxex** [comment]
Found that I'm wrong with backslash, it does not do nothing. With it you can bypass effect of next character, like ' turn red. So translators could make use it immediately, without need of waiting an unescape system.

**Comment by palxex** [comment]
The problem is,  if we support the current whole escape system in title, then the title text color would also be changed, which will conflict with the design of title coloring - separate title from other text.
I propose a new way: in title, let's only support the single quote escape, and it will only have effect of unescaping, no color change implied. Which will makes "Zhao Ling\'er:" displays as "Zhao Ling'er:" with title color, without translators need to notice whether a line is title or text.
Is that enough?

**Comment by Nostaljaded** [comment]
If your proposed solution (of supporting only the single quote escape in 'title') will make "Zhao Ling\\'er:" displays as "Zhao Ling'er:" with title color (without translators needing to notice whether a line is title or text), please go ahead with your solution. :)

**Comment by palxex** [comment]
Since I and @PalMusicFan have both tested and saw no problem, merging the solution and closing the issue. If any other problem found it will be reopened.

**Comment by Nostaljaded** [comment]
@palxex 

Could you make **single quote (') & minus (-) escape to work for 'item & spell descriptions'** sections as well?

![0](https://user-images.githubusercontent.com/28423237/53307050-3a71d580-3862-11e9-8548-6ab838799fda.png)

Like what you did for 'title'.

Thanks.

**Comment by palxex** [comment]
Not as easy as expected, will try find solution on weekend. Reopened.

**Comment by palxex** [comment]
@Nostaljaded Could you please upload a demo language file for testing?

**Comment by Nostaljaded** [comment]
As attached.

Also in 'Found Item' message window, escape character works for apostrophe but not minus.
(Just get the Sabot and Seal Y in the 1st room on new game.)

[m_eng_characterescape.txt](https://github.com/sdlpal/sdlpal/files/2917410/m_eng_characterescape.txt)

**Comment by Nostaljaded** [comment]
Checked in original PAL exe that only the following symbols are recognized as text styling characters.
- double quote ", dollar $, tilde ~ and both parenthesis ().

The following text styling characters are recently added in SDLPAL which I assume is to support mod梦幻版:
- apostrophe ', minus -, at @ 

**If mod梦幻版 is the only one using apostrophe and minus for styling, why not replace both of them with less common symbols?**

Like caret ^, underscore \_, asterisk \*, grave accent ` could be replaced for apostrophe and minus as they are not used in many languages in their written form.
_(I'm currently using '*' for 'sounds' in dialog lines but feel free to use it for text styling.)_

**apostrophe ':** is very common in English and can also be used as 'quotes' in dialogs for Chinese mods and other language translations, since double quotes " is already used as text styling

**minus/hyphen -:** Needed for negative stats in item description and IIRC is also commonly used in French and Russian

**dash —:** is another common one in some languages

**at @:** should be fine as text styling character

Furthermore, text styling does NOT stop automatically at the current message and will overflow till the text styling character is read the next time.
_(New game intro dialog is a good example.)_

**Replacing apostrophe and minus text styling usage with less common symbols (like ^, \_, \*, `) will also make translations easier to maintain, revise and more reader-friendly. :)**

**Comment by palxex** [comment]
Not sure whether I understand correctly, are you suggesting modify the mod梦幻版 resource? The problem is it has been widely distributed more than 10 years, in many file hosting site, and we cannot tell user they need to replace for play with SDLPal:)
Another note, the original EXE already supports apostrophe ', minus - ( though not in text ). Only the at @ was newly introduced in SDLPal. Though 梦幻版 is the most famous original EXE mod, but it is not the only one. Before SDLPal existing there has been more than 10 mod( most of them existing on baidu tieba; though most of them based on 梦幻版, but there're also some other mod like 月影 is not), I'm sure there're at least some mod used the those character. They're all compatible with original EXE and SDLPal now, change it may break them all.

**Comment by Nostaljaded** [comment]
I was not aware there are so many other PAL mods based on 梦幻版.

**Looking at the big picture, instead of displaying the character symbols, it enables 3 more text styling colors in SDLPAL for 梦幻版 and its many derivative mods.**
Judging from the intro lines, PAL ENG dialog lines looks really broken on current SDLPAL.

Presently, I'm maintaining 3 ENG versions (PALDOS text file, PALWIN M.msg & text file).
Besides porting the revised translations to all 3, it will be painful due to:
1. With new behavior of SDLPAL character escape system, ENG M.msg has to diverge from the text file as my intention is for players to still be able to play/test ENG using original Pal.exe.
2. Cannot simply 'Replace All' if character escape system does not apply to 'all escape characters to all sections' as no indication in message file which line is for which section.


An alternative will be to **have a 'UseExtraTextStyling' setting in text file, like UseISOFont**.
Default value to be 1 if UseExtraTextStyling setting line is missing.

As such, all mods would then be able to display correctly the intended text styling, without further code modifications to accommodate specific cases. :)

**Comment by palxex** [comment]
> 2. Cannot simply 'Replace All' if character escape system does not apply to 'all escape characters to all sections' as no indication in message file which line is for which section.

Agree, replace-all not working makes too much maintaining stress. But don't worry, I'll push a new branch today, which focus on resolving it, makes 'Replace All" works again :)
 
> An alternative will be to **have a 'UseExtraTextStyling' setting in text file, like UseISOFont**.
> Default value to be 1 if UseExtraTextStyling setting line is missing.

Let's first test the new branch and then decide whether new option is needed:)

**Comment by palxex** [comment]
Please test the [WIP_unescape_all](../tree/WIP_unescape_all) branch, bintray nightly is building, follow previous url schema.

**Comment by palxex** [comment]
Re-committed tested code in same branch.
Please verify the version hash is d57110a instead of 83974d2(in window title). If unsure, please just delete old build and re-download from https://bintray.com/sdlpal/nightly/WIP_unescape_all/v2019-03-02-gd57110a.

**Comment by palxex** [comment]
Thanks @PalMusicFan testing, add handling for two deduction place, makes sure only visible characters is calculated.

**Comment by Nostaljaded** [comment]
It's probably the same issue raised by PalMusicFan.

**Item Menu is including the escape character '\\' for its character display alignment, which resulted in the 3rd column item quantity to be cut off.**
_Bugged:_
![2](https://user-images.githubusercontent.com/28423237/53689973-8bd10780-3d2f-11e9-9cb1-60f829c56483.png)

_Correct:_
![1](https://user-images.githubusercontent.com/28423237/53689967-6fcd6600-3d2f-11e9-9cee-19aff93dc176.png)

**Spell Menu is including the escape character '\\' to determine whether to be a 2 or 3 column display.**
_Bugged:_
![3](https://user-images.githubusercontent.com/28423237/53689974-8ffd2500-3d2f-11e9-9b4e-402be42a45bb.png)

To reproduce bug:
Replace _Seal X_ with _Seal X789\\-_

**Comment by PalMusicFan** [comment]
Please test 54b9241.

**Comment by PalMusicFan** [comment]
Now please note a tricky point of this implementation is, multiple \ will be replaced to one \ on the screen. But I don’t think we need to display any sentence including \\\\\.

**Comment by Nostaljaded** [comment]
**'Item Menu' is bugged, still in 3-column display for 11-character item name**; 'Spell Menu' correctly changed to 2-column display for 11-character.
_('Item Menu' will only change to 2-column display when there's a 12-character item name.)_

![1](https://user-images.githubusercontent.com/28423237/53771678-91565b00-3eb1-11e9-98dd-03c1726fcc96.png)

**Comment by palxex** [comment]
It's not introduced in this branch, the layouts are different from long ago. So it's better to unify them follow the magic menu way?
Have done in c41815d, please test them once autobuild done.

**Comment by Nostaljaded** [comment]
Minor issue, '\\' cannot be displayed in:

- Spell Name
- Item Name
- Spell Descriptions
- Item Descriptions

_Correct behavior in message window_
![1](https://user-images.githubusercontent.com/28423237/53923122-1b82f880-4045-11e9-8176-d0e5f4a1f124.png)

_Item Menu behavior_
![2](https://user-images.githubusercontent.com/28423237/53923128-2047ac80-4045-11e9-9086-4a0bc17415d4.png)

I've not tested the escape system in 'battle messages', please help to test.

Other than the above 2 scenarios, no issues found. :)

**Comment by palxex** [comment]
Please attach message file for each testing, since unescaping is not fully reversable, at least in this implementation.
Note: only use single back slash `\` for escaping other character. Whenever displaying `\` is needed, use its escaping form `\\`, it will be then unescaped and displays as `\`. 
( In fact, I think the need of displaying `\` - even the single one - should be rare. Tell me if any natural language need it. If so, lets consider completely ignore it in display, it will predigest things much. )
For battle message, it should has no difference than normal message, since both runs though same code path.

**Comment by Nostaljaded** [comment]
**'\\' to show or not is up to SDLPAL team, as long as it's consistent in the messages and menus.**

![1](https://user-images.githubusercontent.com/28423237/53932749-2ea7bf80-4069-11e9-997f-1b311b71f580.png)

![2](https://user-images.githubusercontent.com/28423237/53932752-349da080-4069-11e9-80a3-68f5f36f3215.png)

Whether '\\' will show or not in 'Item Description' is dependent on what is the next character.

[m_eng_win_escape.txt](https://github.com/sdlpal/sdlpal/files/2939544/m_eng_win_escape.txt)

**Comment by palxex** [comment]
Due to the fact whether `\` is required for displaying, we've different ways on making them consistent, which leads to different difficulty of implementing. So let's make it clear first.

**Comment by Nostaljaded** [comment]
I don't think any languages needs `\`, so you can completely ignore it in display. :)

**Comment by palxex** [comment]
Please test the latest commit e2b2429. Finally choose making the fake unescaping behavior same like the original one, avoid more problem, which means back slash will still show, as same as dialog usage.

**Comment by Nostaljaded** [comment]
Should be all good now. :)

**Comment by palxex** [comment]
#151 merged PR, thanks all testers:)

**Comment by xenoghast** [comment]
Has this been solved then, how do I use the PR fix?

**Comment by PalMusicFan** [comment]
This PR was merged, so just use the latest version.

**Comment by xenoghast** [comment]
I have built the linux version, and not the MacOS version. Would this explain why the escape characters still hold the font colors?

**Comment by palxex** [comment]
@xenoghast SDLPal should have same behavior on all platforms. Please upload your message file and screenshots.

**Comment by xenoghast** [comment]
https://www.romhacking.net/translations/2441/
![sdlpal](https://user-images.githubusercontent.com/10499368/57986401-516f3080-7a29-11e9-8af0-3ef104406b85.png)

**Comment by palxex** [comment]
This is expected. The version 3.2 was released before the solution discussed, and the PR does not maintains compatibility, both forward/backward. Please wait a new release of the translation file, or replace `'` with `\'` manually now.
