### ISSUE TITLE
我方使用合击的条件与原版不一致

### ISSUE THREAD

**Issue by alex19861118** [sdlpal/sdlpal#125]
SDLPAL下 我方成员有一个虚弱的话则全员无法使用合击打，如图：
![sdlpal98](https://user-images.githubusercontent.com/29162792/48708606-f73e1000-ec3d-11e8-8e44-13916c3e1aec.jpg)

当DOS和98原版里，一个人时是肯定无法使用合击的，两个人组队一个人虚弱的话就无法合击，三个人的话虚弱一个人的话，剩余2个人依然可以用合击，但是合击伤害会弱于3人合击，如图：
![dos](https://user-images.githubusercontent.com/29162792/48708670-26548180-ec3e-11e8-81f3-67e11738e5f4.jpg)
![981](https://user-images.githubusercontent.com/29162792/48708689-310f1680-ec3e-11e8-8fe8-dc99e830dfd7.jpg)
![qq 20181119210111](https://user-images.githubusercontent.com/29162792/48708717-4421e680-ec3e-11e8-9af5-0f6605a89d4c.png)

但是当3个人中的2个人虚弱或者死亡，剩余的一个依然可以使用合击 但是不会造成任何伤害，也不会播放法术动画，只是人物坐标会移动过去，个人感觉这条应该是原版BUG，如图：
![982](https://user-images.githubusercontent.com/29162792/48709199-c2cb5380-ec3f-11e8-99fc-5f49c3ed535c.png)
![983](https://user-images.githubusercontent.com/29162792/48709204-c8c13480-ec3f-11e8-918e-4004f1960cf8.png)

**Comment by palxex** [comment]
请测试新分支new_coop_model是否解决了此问题，以及是否引入了新问题。
该新分支允许「部分合击」；只要非虚弱成员数目>1，任意非虚弱成员可以发起合击，合击强度由实际合击成员而不是全体队员决定，反伤血亦如此；由此也规避了最后一人自己合击的问题（我也认为这是个bug）。

**Comment by palxex** [comment]
V e
