### ISSUE TITLE
Mojave下编译出来的app当更改窗口大小的时候，显示会错位到右边，左边留下一个大大的黑色区域。不知道是不是Pal代码的bug

### ISSUE THREAD

**Issue by sudormroot** [sdlpal/sdlpal#129]
Mojave下编译出来的app当更改窗口大小的时候，显示会错位到右边，左边留下一个大大的黑色区域。不知道是不是Pal代码的bug

**Comment by palxex** [comment]
请按照说明重发issue，在提示的位置填入cfg，log，资源版本等，重现步骤及（最好有）操作视频。
