### ISSUE TITLE
商店与傀儡状态的问题

### ISSUE THREAD

**Issue by alex19861118** [sdlpal/sdlpal#134]
描述问题：
1.ESC呼出菜单，道具一项的子菜单，原版(DOS\98)是装备在上，使用在下，SDLPAL是相反的。

![qq 20181222211304](https://user-images.githubusercontent.com/29162792/50374765-99cb2380-062e-11e9-94c5-9dc02acab30f.png)
![qq 20181222211309](https://user-images.githubusercontent.com/29162792/50374766-9a63ba00-062e-11e9-91f7-ef5f50f7717a.png)

2.在商店购买物品时，左上角物品图像框没有阴影，左下的现有与金钱框的阴影会随着上下选择物品而加深，原版(DOS\98)不加深，物品价格的颜色也不一致。
![qq 20181222211602](https://user-images.githubusercontent.com/29162792/50374811-ec0c4480-062e-11e9-842a-2bd5b35ded05.jpg)
![qq 20181222211639](https://user-images.githubusercontent.com/29162792/50374826-1958f280-062f-11e9-83e3-33e26b78809f.jpg)

3.激活任意商店，原版(DOS\98)是物品图像、现有、金钱、物品列表同时出现，而SDLPAL是先刷新出物品列表后，其余三项才刷新出来。

4.原版(DOS\98)傀儡状态时，如图，可以给傀儡虫添加各种状态，添加的状态在复活时会被清空，战斗时，我方只剩下傀儡状态的队员则战斗马上失败。
![qq 20181222211238](https://user-images.githubusercontent.com/29162792/50374835-3beb0b80-062f-11e9-91d7-45628f3b87cc.png)
![qq 20181222210255](https://user-images.githubusercontent.com/29162792/50374838-42798300-062f-11e9-957b-37aa3eabc939.jpg)

  SDLPAL傀儡状态时，无法给傀儡添加任何状态，战斗时，我方只剩下傀儡状态的队员，必须等傀儡状态消失后，战斗才会失败。

**Comment by palxex** [comment]
1. 在 3f98e83 中修正；
2. 阴影问题在 cde213f5 中修正。字体颜色应视为增强（增加了选中闪动及对比度），不予修正。
3. 刷新顺序问题：因sdlpal的菜单系统与原版实现差异过大，实现原效果需要的改动很大，又此处差别极微细，暂不考虑。
4. 需要修正，留待。

**Comment by palxex** [comment]
4. 在 f8d2531 中修正。

非常感谢您的汇报，已修正全部可修正部分，因此关闭，有疑问请重开。
