### ISSUE TITLE
sdlpal\win32\win32.cpp(428): error C3861: 'SDL_setenv': identifier not found

### ISSUE THREAD

**Issue by wohenniubi** [sdlpal/sdlpal#136]
2016年pull sdlpal并使用Visual studio 2015成功编译。2019年pull最新的branch，使用Visual studio 2017 打开win32文件夹里面的sln文件，完成设置后编译，在编译win32.cpp时出现以下错误

\1>------ Rebuild All started: Project: sdlpal, Configuration: Debug Win32 ------
1>'git' is not recognized as an internal or external command,
1>operable program or batch file.
1>Generating Git revision header: 01/02/2019 23:51
1>win32.cpp
1>\\mac\home\documents\disk_f\05.code_battle\ccc\sdlpal98\sdlpal19\sdlpal\win32\resource.h : warning C4828: The file contains a character starting at offset 0x2f that is illegal in the current source character set (codepage 65001).
.............
1>\\mac\home\documents\disk_f\05.code_battle\ccc\sdlpal98\sdlpal19\sdlpal\win32\win32.cpp(428): error C3861: 'SDL_setenv': identifier not found
1>native_midi.cpp
1>surroundopl.cpp
1>emuopls.cpp
.............
1>mame_opls.cpp
1>\\mac\home\documents\disk_f\05.code_battle\ccc\sdlpal98\sdlpal19\sdlpal\adplug\mame\fmopl.cpp.h(537): warning C4018: '>=': signed/unsigned mismatch
1>\\mac\home\documents\disk_f\05.code_battle\ccc\sdlpal98\sdlpal19\sdlpal\adplug\mame\ymf262.cpp.h(784): warning C4018: '>=': signed/unsigned mismatch
1>dosbox_opls.cpp
1>Generating Code...
1>Done building project "sdlpal.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

使用的SDL library是SDL.1.2.15，该库可以与之前的sdlpal可以成功编译，不知道是否需要升级到SDL 2.0
感谢答复

**Comment by palxex** [comment]
请仔细阅读readme；在sdlpal仓库下执行git submodule update --init --recursive即可获得sdlpal内置的sdl2及其他依赖库。

**Comment by palxex** [comment]
另外非常感谢报错哈。sdlpal目前还同时支持sdl1/2，但1.x测试已经很少，同时一些新平台比如macOS 10.14已经不再支持，不久的未来可能会去除，但现在还是bug。

**Comment by wohenniubi** [comment]
感谢及时回复。尝试在sdlpal仓库下执行命令，然后再次编译还是出现同样的问题，win32.cpp(428): error C3861: 'SDL_setenv': identifier not found.

| => git submodule update --init --recursive
Submodule '3rd/SDL' (https://github.com/sdlpal/SDL.git) registered for path '3rd/SDL'
Submodule '3rd/googletest' (https://github.com/google/googletest) registered for path '3rd/googletest'
Submodule '3rd/mingw-std-threads' (https://github.com/sdlpal/mingw-std-threads.git) registered for path '3rd/mingw-std-threads'
Cloning into '/Users/Documents/Disk_F/05.Code_Battle/CCC/SDLPAL98/sdlpal19/sdlpal/3rd/SDL'...
Cloning into '/Users/Documents/Disk_F/05.Code_Battle/CCC/SDLPAL98/sdlpal19/sdlpal/3rd/googletest'...
Cloning into '/Users/Documents/Disk_F/05.Code_Battle/CCC/SDLPAL98/sdlpal19/sdlpal/3rd/mingw-std-threads'...
Submodule path '3rd/SDL': checked out '58e943b0610085ead2e943a85dd9daa905f066e9'
Submodule path '3rd/googletest': checked out 'aa148eb2b7f70ede0eb10de34b6254826bfb34f4'
Submodule path '3rd/mingw-std-threads': checked out 'aabf8e384b9d5e1d4f9774865c942f274b7f68d7'

明天还要上班，等待答复。感谢

**Comment by palxex** [comment]
猜测是你之前手动设置sdl1导致的问题。请尝试关闭工程，git reset --hard清空本地修改再打开。

**Comment by palxex** [comment]
不必要，很多人使用v141非xp版编译。
无法重现您的问题，抱歉无法提供进一步的帮助，请等待更熟悉windows的其他人。

**Comment by louyihua** [comment]
@wohenniubi 请打开你的Visual Studio 2017安装程序，将已安装组件的列表截图发上来

**Comment by wohenniubi** [comment]
<img width="347" alt="screen shot 2019-01-05 at 12 03 40 am" src="https://user-images.githubusercontent.com/13992754/50722003-9cda0100-107d-11e9-851a-4ff939fa5651.png">
 您好，以上是vs2017的安装组件，之前的问题在刚刚安装了v14.1_xp的组件之后解决了，现在编译成功。但是遇到下面的问题，
<img width="229" alt="screen shot 2019-01-05 at 12 07 58 am" src="https://user-images.githubusercontent.com/13992754/50722030-fcd0a780-107d-11e9-81cc-84958ca694d9.png">
我仅仅把所有小写的.mkf文件copy到sdlpal.exe所在的文件夹，如下图所示
<img width="745" alt="screen shot 2019-01-05 at 12 12 50 am" src="https://user-images.githubusercontent.com/13992754/50722103-bf204e80-107e-11e9-957b-4ec325c13d7f.png">

**Comment by wohenniubi** [comment]
<img width="641" alt="screen shot 2019-01-05 at 12 29 49 am" src="https://user-images.githubusercontent.com/13992754/50722314-f3e1d500-1081-11e9-87d6-e590a9bdbf56.png">

感谢，最后的问题我搞定了，貌似不仅仅.mkf文件，还需要其他的文件，例如：M.msg和word.dat，然后再直接运行sdlpal.exe就OK了，不过单步跟踪还不行，以后再试试；
还好之前成功编译过这个sdlpal的project，有很多troubshot的整理，希望有机会成为贡献者之一，先睡觉了，2019年，快乐呀～
<img width="704" alt="screen shot 2019-01-05 at 12 36 16 am" src="https://user-images.githubusercontent.com/13992754/50722328-31def900-1082-11e9-85fc-0912450399f0.png">
