### ISSUE TITLE
Difficulty Mode Setting

### ISSUE THREAD

**Issue by Nostaljaded** [sdlpal/sdlpal#137]
The game appeal lies mostly with its storytelling, so requesting a 'Difficulty Mode' setting in sdlpal.cfg (if it's doable). :)

- Adventure (Enemy to have 1 HP, 1 Atk, 1 Def)
- Very Easy (-20% to HP, Atk & Def)
- Easy (-10% to 3 stats)
- Normal/Default
- Hard (+10% to 3 stats)
- Brutal (+20% to 3 stats)
- Custom (individual settings for the 3 stats)

**Comment by palxex** [comment]
Closing due to lack of discussing, logged in wiki, please reopen once needed.
