### ISSUE TITLE
显示设置和wiki上的说明不一致

### ISSUE THREAD

**Issue by luweitest** [sdlpal/sdlpal#139]
我下载了最新的release，启动之后，显示设置只有4项，没有说明中那么多选择，画面锯齿严重
p.s. 这个启动器能够解决midi延音的问题，然而我用dosbox却不行，是我设置问题，还是sdlpal有特别的处理？

**Comment by luweitest** [comment]
附加问题解决了，请无视（帖子编辑功能无效删不了文字，只好再回一次）

**Comment by luweitest** [comment]
按照wiki说明，从https://github.com/libretro/glsl-shaders/blob/master/scalenx/shaders/scale2x.glsl 下載了放到同目录，sdlpal.cfg内容：
KeepAspectRatio=1
FullScreen=0
LaunchSetting=0
Stereo=1
UseSurroundOPL=1
EnableKeyRepeat=0
UseTouchOverlay=0
EnableAviPlay=0
EnableGLSL=1
EnableHDR=0
SurroundOPLOffset=384
LogLevel=0
AudioBufferSize=1024
OPLSampleRate=49716
ResampleQuality=4
SampleRate=44100
MusicVolume=50
SoundVolume=100
WindowHeight=400
WindowWidth=640
TextureHeight=800
TextureWidth=1280
CD=OGG
Music=RIX
OPL=DOSBOXNEW
MessageFileName=C:\green\games\pal\m_eng.txt
LogFileName=C:\green\games\pal\sdlpal.log
Shader=scale2x.glsl

然而sdlpal.exe一启动就崩溃。将EnableGLSL=0可恢复正常。试过其他的几个glsl文件都一样。
需要崩溃报告吗？

**Comment by palxex** [comment]
scalenx/shaders/scale2x.glsl是最早支持的几个shader之一（参见https://github.com/sdlpal/sdlpal/pull/78 合并的测试报告），当前master版本经测试支持没有问题。请给出详细日志文件，方法见wiki。
另外下载的release是github这里的吗？glsl支持目前仍然在测试，尚未进入release，需要测试这部分新功能请自行编译或者下载nightly build，地址见readme顶部。已删除之前用于测试的glsl_test prerelease以免误导。

**Comment by luweitest** [comment]
是的，我下的是glsl_test版。LogLevel=0，但没来得及写任何日志就已经崩溃了。
之前的2017-11的版本我也试过，那个版本在我这里完全不可用（我的系统是WinXP SP3, 仙剑DOS)，运行之后没反应，大概1～2秒即退出，也是没有任何日志输出。

如果glsl支持目前仍然在测试，那2017-11版是用什么实现画面优化的呢？还是只能用320×200的直接放大？

**Comment by PalMusicFan** [comment]
先问一下，楼主您该不会是访问 https://github.com/libretro/glsl-shaders/tree/master/scalenx/shaders/ 之后在scale2x.glsl上右键另存了吧？即直接保存了访问您贴的那个地址所返回的文件？如果是……你用记事本打开之后看到的是html文件内容。
正确的操作，想单独下载这个文件，应该在打开那个页面之后，Raw按钮上右键另存（下载地址是 https://github.com/libretro/glsl-shaders/raw/master/scalenx/shaders/scale2x.glsl ）……用记事本打开以后首先能看到的是以"/*"为开头的注释……

**Comment by luweitest** [comment]
下载了nightly，UI选项多了，使用这里下的plain.glsl，还是崩溃，不过留下了三行log：
2019-00-23 20:43:24   [DEBUG]: SDLPal build revision: v2019-01-20-gde40253
2019-00-23 20:43:24    [INFO]: PAL_DetectCodePage detected code page 'BIG5' for word.dat
2019-00-23 20:43:24   [DEBUG]: requesting to create window with flags: opengl Core profile latest available, framebuffer_sRGB based sRGB gamma correction

**Comment by luweitest** [comment]
@PalMusicFan : 我下载的都是Raw文件，打开看过，格式对的

**Comment by PalMusicFan** [comment]
那么我们来看一下细节吧。
首先请参考模板贴一下您的系统环境信息。
然后，您下载的是哪个版本的？MinGW版还是VC版？能否测试其它版本例如安卓APK？

**Comment by luweitest** [comment]
补充：崩溃是在点了“启动游戏”之后，设置窗口是可以运行的

**Comment by PalMusicFan** [comment]
崩溃有什么提示？
设置窗口并不依赖GLSL渲染。

**Comment by palxex** [comment]
看起来是请求gl环境时直接崩溃了。没有xp环境，这个暂时只能你自己尝试解决了。请报一下可能相关的环境信息，包括显卡硬件和驱动版本（有opengl extension viewer给出的opengl驱动详细信息最好），日后等开发组有条件复原时会尝试解决。
sdlpal在支持glsl前没有filter支持，只能原样放大输出。
另关于midi，不记得sdlpal有特定优化，实际上用默认配置还是有延音踏板的蜂鸣声；我这里都是换其它合成器解决的。

**Comment by luweitest** [comment]
MinGW版：https://bintray.com/sdlpal/nightly/download_file?file_path=v2019-01-20-gde40253%2Fsdlpal-win32-mingw.zip
系统崩溃时的截图：我想贴图但是那个上传按钮不行，只好找了个地方上传：
http://androidhost.org/n28k9zC
系统环境模板哪里有？

**Comment by luweitest** [comment]
这是显卡有关的信息：http://androidhost.org/GTamRW6

**Comment by PalMusicFan** [comment]
XP+965的配置？这个……其它环境测试过吗？
系统环境模板在提issue的时候会有选择。

**Comment by luweitest** [comment]
Thinkpad X61的硬件配置, 老本子玩老游戏，呵呵。这个本子装Win7估计够呛，不打算升级了

dosbox现在用 scaler=hq2x 可以优化画面，声音用CD音源+声霸卡也都正常了。midi的问题或许是网上说的Windows自带波表的问题，一开始是延音蜂鸣声，后来又变成没音乐，反正不用midi就是了。dosbox看起来不用glsl就实现了shader，不知sdlpal可否移植？

当时提issue的时候不知为何没出模板。Github对XP下的Firfox 52ESR已经不支持了，很多功能broken，唉

**Comment by luweitest** [comment]
好吧，既然2017-11老版确定也没有画面优化，那么为什么不能运行的原因也不重要了吧。还是继续用dosbox好了。
SDLPAL的多语言是个很好的功能。物品说明我大致看了看，文字有时有和背景叠加不太清楚的问题。不过这是另一个问题。
正打算在手机上试，有问题再反馈，谢谢！
