### ISSUE TITLE
英文字幕显示颜色不一致

### ISSUE THREAD

**Issue by luweitest** [sdlpal/sdlpal#140]
**To Reproduce / 重现步骤**
1. 新建游戏或载入进度都有这个问题
2. 如何操作：下载 http://www.romhacking.net/translations/2441/ 的英文包，设置语言文件使用其中的m_eng.txt
3. 正常启动游戏
4. 新游戏或者载入进度，进入说话场景，一开始字幕白色，从第二屏开始字幕出现红色字，分布似乎是随机的，每次启动变红色字的位置固定。

**Expected behavior期待的正确结果**
用m_cht.txt没有这个问题，都是白色字幕，应该与之一致。

**Screenshots/Capture 截屏/录像**
https://postimg.cc/rdMBFvKx

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统: WindowsXP, Android MIUI10
 - Device设备: Thinkpad X61, Xiaomi5
 - Version版本:v2019-1-20-gde40253
 - Resource游戏资源: DOS版，不知是否修正版
 - Config配置:

KeepAspectRatio=1
FullScreen=0
LaunchSetting=0
Stereo=1
UseSurroundOPL=1
EnableKeyRepeat=0
UseTouchOverlay=0
EnableAviPlay=0
EnableGLSL=0
EnableHDR=0
SurroundOPLOffset=384
LogLevel=0
AudioDevice=-1
AudioBufferSize=1024
OPLSampleRate=49716
ResampleQuality=4
SampleRate=44100
MusicVolume=100
SoundVolume=100
WindowHeight=400
WindowWidth=640
TextureHeight=400
TextureWidth=640
CD=OGG
Music=RIX
OPLCore=NUKED
OPLChip=OPL3
MessageFileName=C:\green\games\pal\m_eng.txt
LogFileName=C:\green\games\pal\sdlpal.log

 - Verbose Log 详细日志文件：
http://androidhost.org/u2MTPru

**Comment by palxex** [comment]
这是预期的结果。
上下文：https://github.com/sdlpal/sdlpal/issues/121
综述：sdlpal为了支持外塞的mod梦幻版的字体变色（时间久远，不可能再去改了），不得已牺牲了现有的英文版（版本号3.2）的兼容性。已提出新的翻译规范避免此问题，等待英文版适配中。
临时解决方案：手动编辑m_eng.txt，将所有'（单引号）替换为\\'（单引号前面增加一个反斜杠）。

**Comment by luweitest** [comment]
替换后解决了，thank you！
