### ISSUE TITLE
[macOS] 请允许将游戏资源档案塞到 App Bundle 内

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#141]
**你的需求是要解决什么问题？请描述一下。**
该问题主要影响到自编译的 pal.app。自编译的档案在没有数位签名的情况下，用 AirDrop 等方式传到另一个 mac 电脑上、或者在线上下载之后，哪怕你点右键让 GateKeeper 允许其运行，这个 pal.app 也是被系统强制沙箱化的、无法存取与其位于同一目录的游戏资源档案：
![image](https://user-images.githubusercontent.com/3164826/52460285-7fc8ae80-2ba4-11e9-8e83-353d8abff545.png)

**描述你希望的解决方案**
绕开这个限制的唯一作法就是允许游戏资源被塞到 pal.app 这个 bundle 内、且 bundle 名称不见得非得是「pal.app」。

**Comment by palxex** [comment]
bundle化之前有讨论过，因为版权文件有可能被bundle后再分发，造成连带责任，在可以直接执行的情况下暂时不考虑。
问题本身未能重现。以[当前nightly dmg](https://bintray.com/sdlpal/nightly/download_file?file_path=v2019-01-28-gb983b37%2Fsdlpal-macos.dmg)为例，下载后挂载dmg、拖放Pal.app至资源文件夹内后，右键运行（提示刚从bintray下载，确认即可）正常。已收到多个验证报告。
请提交问题build（最好是app本身）、环境、cfg（如果有非默认配置；放在Pal.app同级目录）和log。
测试通过环境（之一）：Mojave 10.14.2, Xcode 10.1。
![2019-02-08 10 36 00](https://user-images.githubusercontent.com/58222/52484703-f93abe00-2bf1-11e9-8a5b-4f94030f1f54.png)

**Comment by ShikiSuen** [comment]
问题发作的黑苹果所运行的系统是 High Sierra 10.13.6，当时跑的档案是我 MacBook Pro 在 Mojave 系统下编译完成、AirDrop 到黑苹果上的。后来我直接在黑苹果上编译之后发现可以运行。但现在我再试图重现该问题的时候却发现无法重现。

考虑到 bundle 化之后对存档的写入、读取权限也是个问题：写在 bundle 外的话，难免被 sandbox 找麻烦；写在 bundle 内的话，会导致主程式签名 notability 失效。所以我先撤回该提案。本讨论串关闭。

**Comment by ShikiSuen** [comment]
F**k xcode 10, period. 
I installed Xcode 9 on macOS Mojave, build the project again, and the mission disappears.
Again, F**k xcode 10, period. 

Case closed temporarily. I suggest holding on any efforts of supporting Xcode 10 until the final version of it releases.
