### ISSUE TITLE
地图迷宫图层块闪现的 bug 又来了

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#142]
**Describe the bug / 描述问题**
之前提报过某些迷宫内主角移动时、有些地图元素忽显忽隐的问题。
当时发现的问题在之后的 build 当中消失了，但我现在发现了新的同类问题。

**To Reproduce / 重现步骤**
0. 使用百游版仙剑 98。
1. 载入进度：[2.RPG.zip](https://github.com/sdlpal/sdlpal/files/2860373/2.RPG.zip)
2. 让角色往左上角走到头，再往右下角走到头，然后再折回来。
3. 你会看到血池有些图层忽隐忽现。

**Expected behavior期待的正确结果**
这些地图元件不该忽隐忽现的。

**Screenshots/Capture 截屏/录像**
![image](https://user-images.githubusercontent.com/3164826/52712656-3cb97180-2fd0-11e9-952d-381657f7e13e.png)
![image](https://user-images.githubusercontent.com/3164826/52712676-4b078d80-2fd0-11e9-9680-0c440ca73a32.png)

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统: Mojave 10.14.3 (18D109)
 - Device设备: MacBook Pro mid-2017 15-inch CTO.
 - Version版本: v2019-01-28-gb983b37
 - Resource游戏资源: 98柔情篇百游下载版
 - Config配置: [sdlpal.cfg.zip](https://github.com/sdlpal/sdlpal/files/2860389/sdlpal.cfg.zip)

**Comment by palxex** [comment]
这个地方是原版地图制作错了，具体错误是：那两个图元设置成了底图元（血池水面）比顶图元（道路半璧）更高。其实用原版exe去跑也能看到，原版也是错的，只是因为重绘范围的问题有一些差异（sdlpal的范围更大，有错杀无错放XD）。
对此类问题，从代码的角度很难去修改。因为很难去把这个错误隔离出来，贸然去改很可能导致现在正常的其他地图反而绘制错了。如果定点去做memory patch，又可能会导致玩家自己绘制的地图出问题，感觉得不偿失。
先提供一个改好的地图吧，原版和sdlpal都不会绘制错误的，大家集思广益一下有什么更好的方式
[map.mkf.zip](https://github.com/sdlpal/sdlpal/files/2865566/map.mkf.zip)

**Comment by ShikiSuen** [comment]
谢谢解释。于是这讨论串结案了吧，至少留作存档已经足够了。

**Comment by guotong1988** [comment]
这个地图编辑器最新版从哪搞？谢谢！

**Comment by palxex** [comment]
就在上文链接里。印象中作者没再更新，不过提供了源代码（vc6的），可以自行修改添加功能。
