### ISSUE TITLE
关于对 macOS 旧系统的支持应对策略的变更

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#143]
该讨论串已经决定用来讨论如何调整这个专案对旧系统的支持。

我现在的想法是这样，不知三位主管怎么看：

一、官方库的编译支持仅保证支持最低 macOS 10.11、且在 Travis_CI 的预设编译环境改为 macOS 10.11、仅编译 x86_64 分支。当且仅当必须要针对「在最新系统下的可运行性」而要做出调整时、再做调整。至于旧版系统 SDK，可以从安装过旧版系统对应的 Xcode Commandline Tools 的系统当中提取，也可直接从相关的 Xcode 版本当中提取……在 Travis_CI 那边也就是一道命令的事情、就可以修改编译用系统与工具套件版本。

二、对于 macOS 10.10 及更旧的系统，仅在相关的说明手册当中点明可能性（纵使 SDL2 框架得在 macOS 10.11 及以后的系统当中编译，但编译而成的框架档案是可以在旧系统当中正常调用的……不然官方不会说从 macOS 10.05 开始支持）、但不在目前这个仓库提供支持。

> 在下同时建议对此感兴趣者使用这个方案：不是要 folk 这个 sdlpal 主仓库，而是新建一个专门的副仓库、且在该仓库的本地作业当中自动 clone 咱们目前这个 sdlpal 主仓库。这样可以减轻副仓库的运维压力、使得副仓库的每个 commit 都仅专注于旧系统编译支持。

三、对于最新的 Xcode，当且仅当一个新版本的 Xcode 发布之后的次年的九月、十月份的 Apple Special Event 的时候、再著手實現目前的专案在该版本的 Xcode 系统上的可编译性。这是为了尽量避免**被新版 Xcode 所可能包含的 bug、或者尽量不受其过河拆桥的特性所限制**而浪費時間。（我测试 Xcode 10.01 在 Mojave 10.14.3 系统下编译出来的东西，哪怕用了旧版系统的 SDK，拷到其它 High Sierra 系统下都会出现找不到游戏资源的问题。）

四、彻底放弃 SDL1 的支持，且相关专案档案从该仓库排除。如果有谁感兴趣的话，可以自己研究这个仓库的历史 commit。

---------------原想法，已经废弃：--------------
SDL2 不支持任何低于 macOS 10.05 的系统，目前继续维护 PowerPC 版的可编译性显然没有意义。
SDL1 相比 SDL2 而言的图形效能太恶劣。

但目前这个专案的 SDL2 分支无法正常用 macOS 10.07-10.10 的 SDK 编译：
![image](https://user-images.githubusercontent.com/3164826/53284786-f3b5aa00-3793-11e9-887b-c87151eb97e6.png)

我在想，要不要将这 SDL2 的 XcodeProj 单独脱离一份（给 macOS 10.7-10.10 专用、使用公版 SDL2 Framework）、使其去掉对 Metal Framework 的依赖？这样的话就可以彻底甩掉对 SDL1 的支持了。

**Comment by ShikiSuen** [comment]
本讨论串仅讨论 macOS 版本。

**Comment by palxex** [comment]
Metal需求并非sdlpal glsl需求的修改引入，而是SDL 2.0.9本身引入的，正如其Windows/Linux版引入的Vulkan需求。往前看吧，需要在旧版编译的注定需要自己修改。

**Comment by ShikiSuen** [comment]
我用 SDL2 的早期版本对照 SDLPal2 的早期专案 commit 试试看（顺便同步之后与 SDL Framework 无关的游戏更新及 Bug 修正）。话说如果这次 Apple 真的是在从 Intel 迁往 ARM 平台的话，那恐怕又是一次双核四架构的鸡掰年代、届时的维护压力可就非得抛弃 macOS 10.7-10.10 不可了。

**Comment by ShikiSuen** [comment]
@palxex @CecilHarvey @louyihua
我最新的想法已经在一楼更新了，不知你们三位主管有何看法。

**Comment by palxex** [comment]
关于无法在其他机器运行这个问题，还是建议上传一个确认有此问题的build上来，由其他人尝试重复和分析。因为目前这个问题并不清楚成因，就难以弄清何种处理方式为宜。
macOS SDL1编译因为目前苹果策略的原因确实已经无意义（白屏），可以择日从travis中取消。但SDLPal中整体性的剔除SDL1尚需时日；目前尚有在主干中的移植（3DS、wii）只有SDL1支持，而我个人寄予厚望的libretro-SDL2 API转接项目距离成熟目前还遥遥无期，在没有替代方案的情况下直接取消SDL1支持对这部分用户就等于被抛弃了。所以完全剔除SDL1个人觉得暂时还只能作为远景规划。

**Comment by ShikiSuen** [comment]
> 关于无法在其他机器运行这个问题，还是建议上传一个确认有此问题的build上来，由其他人尝试重复和分析。因为目前这个问题并不清楚成因，就难以弄清何种处理方式为宜。

这个问题可以等 Travis_CI 啥时候支持 macOS Mojave 之后、在那边 build 出来试试看。另外 paizhangpi 手头可能有我早期给他的问题拷贝，我去问他要一份看看。

> macOS SDL1编译因为目前苹果策略的原因确实已经无意义（白屏），可以择日从travis中取消。但SDLPal中整体性的剔除SDL1尚需时日；目前尚有在主干中的移植（3DS、wii）只有SDL1支持，而我个人寄予厚望的libretro-SDL2 API转接项目距离成熟目前还遥遥无期，在没有替代方案的情况下直接取消SDL1支持对这部分用户就等于被抛弃了。所以完全剔除SDL1个人觉得暂时还只能作为远景规划。

这个讨论串仅讨论 macOS 部分，也就是说仅删除 macOS 资料夹下的 SDL1 相关档案支持。Travis 那边用的是 macOS 10.13 SDK，所以编译出来的 SDL1 版 SDLPal 可以跑、也没有空白画面的问题（dark mode 下该问题画面是灰画面），但 SDL1 在 macOS 系统下的萤幕绘制效率实在令我难忍。我在这个讨论串的任何提议均不涉及其它平台对 SDL1 的可能的依赖。

**Comment by ShikiSuen** [comment]
[Pal_Buggy.zip](https://github.com/sdlpal/sdlpal/files/2922589/Pal_Buggy.zip)
@palxex 问题 build 在此，这个 build 目前在我的（已经删掉 Xcode 10 的）Mojave 系统下也找不到游戏资源档案了。

**Comment by ShikiSuen** [comment]
我发现这个 bug build 与 gatekeeper 有一定关系。
我的游戏是放在一个 ExFat 卷宗当中的，这样不会受 HFS+ / APFS 权限影响。
这个 zip 放在这个卷宗内的游戏目录下就地解压的话，pal.app 死活不会找到游戏档案。
但要是放在这个卷宗外执行过一次、再放到这个卷宗内的游戏目录下的话，就又可以用了。
很谜。

**Comment by palxex** [comment]
在exfat上就地解压了还是无法重现- -本来准备能重现的话用dtruss仔细分析一下的。
看来暂时只能当悬案了。

**Comment by CecilHarvey** [comment]
macOS的SDL1那个当年早已删除了，后来为了用osx 10.4测big endian加回来的 - -
可以删除。

**Comment by ShikiSuen** [comment]
> 在exfat上就地解压了还是无法重现- -本来准备能重现的话用dtruss仔细分析一下的。
> 看来暂时只能当悬案了。

你的系统卷宗用 FileVault 加密了没？我这边系统卷宗是加密的。

**Comment by palxex** [comment]
> 你的系统卷宗用 FileVault 加密了没？我这边系统卷宗是加密的。

没有。机械硬盘不准备再加这个进一步降低性能了。理论上说此类框架对上层应用都应该是透明的，嗯，理论上。

**Comment by palxex** [comment]
Closing due to lack of discuss, let's reopen it once any news occur.
