### ISSUE TITLE
Resource HASH INFO of MESSAGE FILE / 为语言文件加入资源校验值信息

### ISSUE THREAD

**Issue by PalMusicFan** [sdlpal/sdlpal#149]
**Is your feature request related to a problem? Please describe. 你的需求是要解决什么问题？请描述一下。**
A MESSAGE FILE does not work for SSS.MKF versions that not compatible with it. So, maybe there should be a mechanic to identify the version of SSS.MKF that a certain MESSAGE FILE made from. 
语言文件不能配合不兼容的SSS.MKF资源文件工作。因此，也许应该引入一种机制来标示制作语言文件时的SSS.MKF版本。

**Describe the solution you'd like 描述你希望的解决方案**
A new section of MESSAGE FILE should be there to store the meta data like CRC32 of SSS.MKF. 
语言文件里增加一个新的部分来存储类似于“SSS.MKF的CRC32”之类的信息。

**Additional context 其他上下文**
Since it is a bit complex to implement the real HASH check function in the project (it should be in the configuration page, and it should be optional, not forced), perhaps basic meta section specification could be implemented first so users could do HASH check manually. 
因为真正为工程实现校验检查功能比较复杂（比如，这个功能得在设置界面实现，而且是可选的，不能是强制的），所以可以先定下META部分的规格以便用户手工检查？

**Comment by PalMusicFan** [comment]
I designed a section to contain information of the MESSAGE FILE. 
我设计了一个段来包含这些信息。
Example: 
例如这样：

LANGUAGE=English
VERSION=3.3
CREDIT=Translator_1; Translator_2; Translator_3
LINK=https://somewhere.org/page.html
INFORMATION=Other words, etc. 
SDLPAL_VERSION=v2019-03-03-g725f385
SSS_MKF_CRC32=e51b297a
INDEX_MKF_CRC32=2466c6c2
M_MSG_CRC32=41a4e961
WORD_DAT_CRC32=69e4e716

Items of CRC32 could be calculated by makemessage.py, while other items should be be filled manually. 
CRC32的项目可以由makemessage.py自动计算，其它项目要人工填写。

Is this section OK? How should we name it? INFO? META? HEAD? 
这个段可以吗？应该如何命名？INFO？META？HEAD？

@Nostaljaded @CecilHarvey @louyihua @palxex

**Comment by PalMusicFan** [comment]
I will send a PR after the section name is determined. 段的名字确定后，我发一个PR.

**Comment by palxex** [comment]
Closing due to lack of discuss, let's reopen it once needed.
