### ISSUE TITLE
支持 Dark 模式之后会在 Retina 模式下过度放大游戏视窗画面

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#150]
这个问题我一直以为是 Xcode 10 导致的。直到我最近一次 commit 为 macOS 10.11-10.13 SDK 编译新增 macOS Mojave 的 Dark Mode 的支持之后、我发现这个问题又来了、且无论系统是否处于 Dark 模式都会发作。

**重现步骤**
让 info.plist 至少出现这两行（可能由 Xcode 10 自动添加，也可能手动添加）：
```
	<key>NSRequiresAquaSystemAppearance</key>
	<false/>

```
**Expected behavior期待的正确结果**
游戏画面不该过度放大，无论当前系统是否处于 HiDPI 模式。

**Screenshots/Capture 截屏/录像**
![image](https://user-images.githubusercontent.com/3164826/54193351-d5221380-44f4-11e9-813b-1d542f15b4b7.png)

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统: macOS Mojave 10.14.3
 - Device设备: MacBook Pro 15-inch mid-2017
 - Version版本: f8bee93 
 - Resource游戏资源 百游 WIN95。
 - Config配置 
[sdlpal.cfg.zip](https://github.com/sdlpal/sdlpal/files/2956361/sdlpal.cfg.zip)

**Comment by palxex** [comment]
请测试最新master( 725f385 )是否解决了此问题。

**Comment by ShikiSuen** [comment]
直接測試 bintray 的檔案，問題沒能重現。

**Comment by palxex** [comment]
Do you mean problem gone? Or it still there.

**Comment by ShikiSuen** [comment]
Problem solved.

I recompiled the code against macOS 10.11 SDK, and I believe that the issue is gone.
