### ISSUE TITLE
打完火麒麟程序自动跳出

### ISSUE THREAD

**Issue by luweitest** [sdlpal/sdlpal#152]
[bug.zip](https://github.com/sdlpal/sdlpal/files/2999955/bug.zip)

**Describe the bug / 描述问题**
打完火麒麟程序自动跳出

**To Reproduce / 重现步骤**
1. 载入进度 
2. 打败火麒麟，阿奴说“变成人了耶”了之后，程序跳出，无法继续。

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统:  Android 8 MIUI 10.2 
 - Device设备: MI5
 - Version版本 v2019-03-03-gc0350f1
 - Resource游戏资源 DOS original 
 - Config配置 已上传
 - Verbose Log 详细日志文件 已上传

**Additional context 其他上下文**
经尝试，不用外挂message文件可避免跳出，外挂文件汉语和英语都会跳出

相关文件已上传，bug.zip内三个文件。
今天测试时出现另一种情况，是情节会继续，但是火麒麟紧接着说的话少了一句，“咳，怪不得嗓子里痒”那句。似乎和保存log文件切换有关，或者跟反复改设置有关。与此可能相关的是显示的字体有时是稍扁的原字体，有时是稍大的字体，似乎设置改了之后就会变化，但外挂字体的选项我从来没动过。

**Comment by palxex** [comment]
已重现。经git bisect二分查找回归确定问题为 b14395b 引入。经调试该问题由语言文件生成/使用两端理解不一致导致特定边界情况下指针越界，具体错误表现形式根据指针被（错误）指向的位置（及ASLR影响）有一定区别，不影响问题定性。感谢测试！
请测试 WIP_eid_fix 分支是否解决了问题。

**Comment by luweitest** [comment]
是的，WIP_eid_fix已解决此问题，谢谢！
