### ISSUE TITLE
Please update the certificate / 请更新证书

### ISSUE THREAD

**Issue by PalMusicFan** [sdlpal/sdlpal#155]
The certificate of /winrt/SDLPal.UWP/SDLPal_TemporaryKey.pfx is about to expire. Would you please update it? 
证书 /winrt/SDLPal.UWP/SDLPal_TemporaryKey.pfx 即将过期。可否更新？

**Comment by palxex** [comment]
Is it possible leave an updater script in scripts folder? If it could be execute in posix systems that's better, but windows CLI is enough too.
@louyihua

**Comment by louyihua** [comment]
@PalMusicFan Certificate is updated with a 10-year period
@palxex Scripts are added for both posix & windows

**Comment by palxex** [comment]
:+1: Resolved perfectly. Closing the issue.
