### ISSUE TITLE
Bug in ui.c PAL_CreateBoxInternal

### ISSUE THREAD

**Issue by weizhang1999** [sdlpal/sdlpal#158]
Lines 40 and 41 in ui.c:
	lpBox->wHeight = (WORD)rect->w;
	lpBox->wWidth = (WORD)rect->h;
The width and height have been swapped.

**Comment by BootlegPhil** [comment]
I suggest possibly doing a fresh install.

**Comment by palxex** [comment]
Closing due to current code actual works. Maybe history problem.
