### ISSUE TITLE
ScaleQuality configuration does not work

### ISSUE THREAD

**Issue by zengxu-yang** [sdlpal/sdlpal#160]
ScaleQuality=1 in sdlpal.cfg does not work. It always uses nearest pixel sampling.

OS: Linux

From line 207 in video.c
```c
if(!gConfig.fEnableGLSL)
    SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, gConfig.pszScaleQuality);
gpTexture = gRenderBackend.CreateTexture(render_w, render_h);
SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "0");
```

It is always overwritten to 0 regardless of the configuration. (line 210) I tried to comment it out to make it work.

**Comment by palxex** [comment]
Please try whether current master resolved it.

**Comment by zengxu-yang** [comment]
Thanks. It works now on my computer.
