### ISSUE TITLE
可以考虑出一个wasm版本

### ISSUE THREAD

**Issue by ananclub** [sdlpal/sdlpal#161]
这样可以在浏览器玩了

**Comment by ananclub** [comment]
好像已经有了.sorry

**Comment by palxex** [comment]
刚看到- -目前有一个简陋的emscripten porting，默认编译到wasm，在测试过的大多平台上（除了IE）能用，但有一堆问题：
1. 音频部分工作不正常（还是概率性的；因为尝试调试时wasm source map实在太不稳定一直没找到原因，代码里只好一禁了之）。
2. 没有设计，用的emscripten默认生成的页面；理想情况下应该设计成一个（更完善点的）SPA。
3. IO完全依赖preloading package，也没有存档功能。理想情况下应该允许用户指定资源包网址，XHR之并cache到local storage，在此基础上能导入/导出存档更佳。
4. 缺乏其他多数平台具有的运行时配置能力，比如本次要用的GLSL Shader（这部分倒是正常得可以……但目前只能每次修改配置文件后重新对所有资源打包后从头下载，原因见3）

无奈时间和能力有限……欢迎提PR哈。

**Comment by palxex** [comment]
更新一下情况。
1. 音频部分已随emscripten更新解决，推测是wasm asyncify的作用
2. 见3
3. Whistler兄重新设计了页面；现在以indexDB作为存储，不再受限于后端；可以上传（每次累积）任意zip、下载存档、清空。
4. 仍缺配置能力，但可以每次上传新的cfg(zip)来变相实现配置更改，不再需要整体打包

问题：
1. 无法支持macOS finder打包的zip，原因未知；mac用户可用命令行打包
2. glsl经更新已重新支持，但可用范围较本地端缩减，全平台safari、macOS firefox尚无法正常运行
3. opus支持尚未添加

**Comment by flyher** [comment]
@palxex 
请教一下大佬，sdlpal.js 的代码是生成的还是手写的呢？

**Comment by palxex** [comment]
@flyher 不敢。wasm是直接以emscripten编译后生成的，这毕竟是个本地代码项目。

**Comment by flyher** [comment]
@palxex  感谢回复，可能我表达不太清楚。web的demo里不是有 `sdlpal.js` ,`sdlpal.wasm` 和`sdlpal.wasm.map`三个文件么，后两者是wasm是直接以emscripten编译生成的，`sdlpal.js`是手写的吧?

**Comment by palxex** [comment]
其实也是生成的。最早的时候连sdlpal.html都是生成的，whistler为了加jszip接管了这部分，只让emscripten生成js，并在参数里要求emscripten将直接生成wasm加载。整个demo的编译和上传流程可以在.travis.cfg里看到。
按我的理解（前端不是很熟- -），js部分是作为wasm加载的软环境，负责wasm里的逻辑代码与浏览器环境的互相沟通，而且是随着emscripten版本前进不断演化的，再予以接管并不明智。

**Comment by flyher** [comment]
@palxex  明白了，thx。

**Comment by bitmori** [comment]
> 无法支持macOS finder打包的zip，原因未知

可能是macOS finder打包时会包入大小为0的隐藏文件，似乎是这些隐藏文件造成jszip工作不正常。
我今天偶然发现这个问题，复现方法非常简单，只要添加任意大小为0的空文件到zip中，无论什么平台的都不行。

**Comment by palxex** [comment]
> 可能是macOS finder打包时会包入大小为0的隐藏文件
原来如此，感谢解惑。不过修改js库就非我所能了，回头看看jszip那边能不能提issue
