### ISSUE TITLE
High Resolution PAL

### ISSUE THREAD

**Issue by fengwang** [sdlpal/sdlpal#162]
Please submit your issue in English or Chinese.
请使用中文或英文提交问题。

**Is your feature request related to a problem? Please describe. 你的需求是要解决什么问题？请描述一下。**
A clear and concise description of what the problem is. Ex. "original DOS/Win95/SS version has a function that SDLPal lacks", or "I think [...] function of SDLPal could be enhanced ".
请清晰明了地描述问题所在。比如「DOS/Win95/SS原版有xxx功能，SDLPal没有」，或者「我感觉xxx功能可以增强」。

当前游戏只能在十几年前的原分辨率下运行．高分辨率基本是当代游戏的标准配置，如果能够在　sdlpal 中得到支持，则可能吸引更多的玩家．

**Describe the solution you'd like 描述你希望的解决方案**
以基于深度学习的超分辨率算法处理游戏素材，然后根据这些高清素材重绘界面．

**Describe alternatives you've considered 描述另一个可选的解决方案**
如果屏幕直接是可以获取的，直接从内存中修改也是可行．

**Additional context 其他上下文**
尝试了直接把游戏视频做高分辨率，效果不佳．可能是因为游戏是８位色的，而神经网络是在　２４　位色下训练的原因．

**Comment by palxex** [comment]
关于画面增强，SDLPal已实验性支持RetroArch Shader（GLSL版），一个示例效果：
![屏幕快照 2019-06-30 上午11 17 03](https://user-images.githubusercontent.com/58222/60391763-b2aa1980-9b28-11e9-910e-817d3de95355.png)
关于游戏素材，SDLPal只是支持玩家使用其已通过购买获得使用权的版权素材，没有修改乃至再分发的立场。
关于超分辨率重建，基于个人视野所及，现有的方法（各种SRCNN）可以概述为：先有高分素材，然后降低之，基于后者以前者为目标进行训练。对SDLPal支持的对象来说，首先的问题是对应的高分素材并不存在。而对非物理着色游戏来说，画面风格化这一目标本身就决定了使用其他来源的预训练NN未必是合适的，除非确定能找到同风格的训练材料。

**Comment by fengwang** [comment]
> 关于画面增强，SDLPal已实验性支持RetroArch Shader（GLSL版），一个示例效果：
这个看起来已经不错了，但是似乎还是可以继续完善，有没有具体实现的说明？
> 关于游戏素材，SDLPal只是支持玩家使用其已通过购买获得使用权的版权素材，没有修改乃至再分发的立场。
可以考虑嵌入一个超分辨率的算法到游戏中去，实时实现超分辨率。算法独立于数据/版权素材存在。当然为了效率可以考虑使用缓存。
> 关于超分辨率重建，基于个人视野所及，现有的方法（各种SRCNN）可以概述为：先有高分素材，然后降低之，基于后者以前者为目标进行训练。对SDLPal支持的对象来说，首先的问题是对应的高分素材并不存在。而对非物理着色游戏来说，画面风格化这一目标本身就决定了使用其他来源的预训练NN未必是合适的，除非确定能找到同风格的训练材料。
Indoflaven 使用一些漫画作为 training set 实现了暗黑2的超分辨率，效果看上去不错。<https://www.reddit.com/r/GameUpscale/comments/bmrkit/diablo_2_upscale/> 或许可以参考一下。

**Comment by palxex** [comment]
看了下这个项目是基于esrgan的，之前看到作者解释过这个项目设计上没有考虑过实时用途https://github.com/xinntao/BasicSR/issues/11。目前跨平台的实时超分辨率重建还是一个相对前瞻的问题，如何在保持统一接口的前提下充分利用本地硬件加速也是，个人感觉宜暂时保持观望，当然PR是永远欢迎的。
关于shader滤镜系统的设计和实现可以参阅当时的PR：https://github.com/sdlpal/sdlpal/pull/78 等。该系统的shader spec与上文reddit帖内提到的cnc-ddraw项目使用的upscale shader为同一规范，上图为当前大多数平台能跑得动也能明显看出一定效果的xbrz-freescale滤镜，对更好的设备可以探索下其它现成的滤镜，也可以自行撰写，shaders目录下有几个例子。这是个独立实现，文档阙如，测试也不太充足，欢迎继续完善。

**Comment by palxex** [comment]
因讨论结束关闭，之后若有必要再开。
