### ISSUE TITLE
读取最后一次存档与原版不一致

### ISSUE THREAD

**Issue by PalAlexx** [sdlpal/sdlpal#165]
Please submit your issue in English or Chinese.
请使用中文或英文提交问题。

**Describe the bug / 描述问题**
存档是DOS3.1修正版在剑柱与明王的战斗，
在SDLPAL里会发生下面的问题

如果被明王打败，从剑柱的场景走出去，然后再次走进来会直接触发把灵儿从剑柱救下来与明王开战的脚本，而跳过了原本的一大段回忆

就是，如果当前正在执行该场景的脚本，这个脚本当中的0000之前出现了0x4e载入最后一次存档（比如有战斗，战败了），调取存档后，场景脚本不会还原到SSS里面的而是新设置的。。。

**To Reproduce / 重现步骤**
1. New game / load save (in this case, upload your save file here) 是新建游戏还是载入进度（后者情况下请上传存档)
[5.zip](https://github.com/sdlpal/sdlpal/files/3365323/5.zip)
2. Let Player Charactor do ... 如何操作
战斗开始全体九阴散自杀，此时会读取最后一次存档

3. Continue operation ...后续步骤
从剑柱走出去，在从外面走进来

4. See problem 出现了什么问题
原有的场景脚本被改变了 

**Expected behavior期待的正确结果**
请清晰明了地描述期待的正确行为。

希望与原版一致
就是载入最后一次存档时当前场景的场景脚本与SSS维持一致 而不是中途被重新设置过的

**Screenshots/Capture 截屏/录像**
如果可能，请提交截屏/录像来更直观地描述问题。

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统: Win10 18932
 - Device设备 [e.g.比如 iPhone 8 Plus / Oneplus 6T / Asus ZenBook3 UX490UA]
 - Version版本 [e.g.比如 v2.0.2017.1114-149-gd0bf681f-dirty / v2018-11-03-g5adba12]
 - Resource游戏资源 [e.g. DOS original / DOS debug patch 3.1 / Win95 original / Win95 China mainland original / Win95 baiyou / baiyou+eng-translate 3.0 比如DOS原版/DOS修正3.1版/Win95台澎金马原版/98柔情篇光盘原版/百游下载版/百游下载版+英文补丁3.0]
 - Config配置 [upload your sdlpal.cfg here, or screenshot of config page on mobile versions 上传你的sdlpal.cfg，或者手机版配置页面的截图]
 - Verbose Log 详细日志文件 [ see [FAQ](../wiki) for steps; upload it here]

**Additional context 其他上下文**
请在此追加觉得可能与此问题相关的任何细节。

**Comment by palxex** [comment]
已重现。问题出在场景进入脚本的处理上；4e指令载入存档时已正常还原场景进入脚本地址，但该场景下脚本执行流本身处在一个场景进入脚本内，此类场景要求以返回值更新地址，而此脚本的返回本身从栈内返回了本应被覆盖掉的原进入地址；这是一个典型的重入导致的条件竞争问题。已构造条件解决此特定情况。
