### ISSUE TITLE
打开系统菜单商店时与原版不一致

### ISSUE THREAD

**Issue by PalAlexx** [sdlpal/sdlpal#166]
打开菜单时有个肉眼可见的刷新过程

视频链接如下:
https://www.youtube.com/watch?v=gsxijpU29uQ

视频里画面左方的是现在主干的代码 

codeplex时期的代码则没有这个现象

**Comment by palxex** [comment]
已在mingw下编译当前master代码的SDL1版确认与codeplex时期表现相同。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShikiSuen** [comment]
@PalAlexx 
那个刷新效果是当年的硬体效能缺陷与编程技术不足使然。
没必要在如今的情况下刻意模拟这种效果。

**Comment by PalAlexx** [comment]
@ShikiSuen 
刷新的是SDLPAL- - 
原版正常的。

**Comment by palxex** [comment]
上面可能没说清楚，之前测试发现当前代码下sdlpal在SDL1下并无此问题，问题描述应改为“sdlpal在sdl2下若干菜单开启/关闭过程刷新过慢肉眼可见”。问题成因推测是sdl2渲染部分设计上需要高刷新率，而sdlpal目前代码因为原版帧率只有10fps以及兼容sdl1的考虑很多地方还是手动刷新的（2D游戏通病，菜单可视为0fps）。research分支尝试了将逻辑帧率与渲染帧率分离，将后者提升到显示器支持的极限，其编译结果经测试可以解决这个问题，但其带来了CPU占用大幅提高的新问题（高刷新率显示器下开多pass GLSL的情况下显存位宽也可能成为瓶颈），对低配机器用户不友好。暂时解决方案是对刷新率敏感的请使用那个分支的自动编译，离主干太远时可在此申请rebase。主干还是等等看有没有两全其美的办法。

**Comment by louyihua** [comment]
@PalAlexx 你可以试一下 louyihua/issue-166-fix 分支是否可以实现你希望的效果

**Comment by PalAlexx** [comment]
@louyihua 谢谢测试过 问题解决了 感谢
