### ISSUE TITLE
Can anyone bulid a release from the recent branch?

### ISSUE THREAD

**Issue by sunszl** [sdlpal/sdlpal#168]
The leastest released one is in 2017. Can anyone help us to build one?
for we want to play it one 3ds,android or  switch. Because we don't have a build environment.

**Comment by PalMusicFan** [comment]
Please use the nightly builds: 
https://bintray.com/sdlpal/nightly/master/_latestVersion
Note that there is no switch version here since it’s maintained by 3rd developer(s).

**Comment by PalMusicFan** [comment]
In fact there is a button in the README area. 

[ ![Download](https://api.bintray.com/packages/sdlpal/nightly/master/images/download.svg) ](https://bintray.com/sdlpal/nightly/master/_latestVersion)

**Comment by sunszl** [comment]
thank you f

**Comment by palxex** [comment]
Closing due to problem resolved.
