### ISSUE TITLE
Fatal Error on Linux (Could not initalize global data: -1, Launch setting dialog on next start?)

### ISSUE THREAD

**Issue by BootlegPhil** [sdlpal/sdlpal#169]
**Describe the bug / 描述问题**
Whenever I try to use the "sdlpal-linux" file to play the game with [the English translation](http://www.romhacking.net/translations/2441/), I get an error message saying

Fatal Error 
Could not initalize global data: -1.
Launch setting dialog on next start?

**To Reproduce / 重现步骤**
1. Replace the Sword and Fairy DOS game files with the ones from the English translation.
2. Place the "sdlpal-linux" file in the same folder as the game files.
3. Try to play the game by clicking on the "sdlpal-linux" file. This is where the error message comes in.

**Expected behavior期待的正确结果**
The game should have opened normally.

**Environment (please complete the following information):**
 - OS: Pop!_OS 19.10
 - Device: Dell Inspiron 15 7000 Gaming Laptop (with i7 CPU, GTX 1060 GPU, and 16 GB of RAM)
 - Resource: Original DOS game files
 - Config: [Config File.zip](https://github.com/sdlpal/sdlpal/files/3799998/Config.File.zip)
 - Verbose Log: The Wiki is only in Chinese, so I have no idea how to get a verbose log.

**Comment by PalMusicFan** [comment]
Have you tried to compile the source code on your system?

**Comment by PalMusicFan** [comment]
Have you tested the official freeware version of PAL98? 
P.S. You could use online translation tool to show the wiki at the moment.

**Comment by louyihua** [comment]
You probably have a mixed version of game resources which contain both DOS resources & WIN resources. Could you execute 'ls -l' under the directory you place the game resources, take a snapshot of the file list and paste the snapshot here?

**Comment by BootlegPhil** [comment]
> You probably have a mixed version of game resources which contain both DOS resources & WIN resources. Could you execute 'ls -l' under the directory where you place the game resources, take a snapshot of the file list and paste the snapshot here?

![Snapshot](https://user-images.githubusercontent.com/49907759/68125443-45900180-fed7-11e9-948a-e26662ad81cb.png)

**Comment by PalMusicFan** [comment]
This is not the DOS version. Please try the game without English patch first, then use files in the directory of "win_files". 
P.S. Pay attention to the letter case of the file name!

**Comment by BootlegPhil** [comment]
> This is not the DOS version. Please try the game without English patch first, then use files in the directory of "win_files".
> P.S. Pay attention to the letter case of the file name!

Thank you. Using the win_files from the English patch worked for me. Closes #169.
