### ISSUE TITLE
Need help! I've got some troubles when compiling the game...

### ISSUE THREAD

**Issue by bigbryant** [sdlpal/sdlpal#17]
Hi I'm Chen. I've got some problems when I was trying to compile sdlpal under WIN10 64bit system using mingw32. I get into the folder win32 and type make -f Makefile.mingw, I will stuck here

In file included from ../common.h:38:0,
                 from ../main.h:25,
                 from ../text.c:27:
D:/CodeBlocks/MinGW/include/wchar.h:119:37: note: expected '__builtin_va_list' but argument is of type 'LPWSTR'
 _CRTIMP int __cdecl __MINGW_NOTHROW vswprintf (wchar_t*, const wchar_t*, __VALIST);
                                     ^
../text.c:2023:15: error: too many arguments to function 'vswprintf'
     cur_cnt = vswprintf(buffer, buffer_end - buffer, cur_fmt, apd);
               ^
In file included from ../common.h:38:0,
                 from ../main.h:25,
                 from ../text.c:27:
D:/CodeBlocks/MinGW/include/wchar.h:119:37: note: declared here
 _CRTIMP int __cdecl __MINGW_NOTHROW vswprintf (wchar_t*, const wchar_t*, __VALIST);
                                     ^
In file included from ../common.h:44:0,
                 from ../main.h:25,
                 from ../text.c:27:
../text.c:1981:31: warning: 'WCHAR' is promoted to 'int' when passed through '...'
       chr_buf[0] = va_arg(ap, WCHAR);
                               ^
../text.c:1981:31: note: (so you should pass 'int' not 'WCHAR' to 'va_arg')
../text.c:1981:31: note: if this code is reached, the program will abort
Makefile.mingw:37: recipe for target '../text.o' failed
mingw32-make: *** [../text.o] Error 1

There are few warnings and errors. How can I fix this?
Thx! Best regards!

**Comment by louyihua** [comment]
Can you tell us what version of MinGW you're using now?

**Comment by bigbryant** [comment]
I dont know the exact way to get the version of MinGW. But I found a version number 4.9.2 in its /bin folder, so I guess it should be 4.9.2, isn't it?

**Comment by palxex** [comment]
According to http://stackoverflow.com/a/8542221/8543540#8543540, seems its a old-flavor MinGW problem. Try replace the toolchain follow the guide of http://stackoverflow.com/a/12808650/27688821#27688821

**Comment by palxex** [comment]
Any feedback? I'm closing it, if still have problem lets reopen it.
