### ISSUE TITLE
Can we have ipk files for linux？

### ISSUE THREAD

**Issue by kinghtt** [sdlpal/sdlpal#171]
Could you please guide how to get an ipk file to use on linux？

thanks

**Comment by palxex** [comment]
Sorry for the late reply.
Not sure which ipk format you refer to? Afaik only openwrt has an ipk format, which seems not a suitable target.
If you refer to any x86-64 linux distro, we've planed add AppImage support in near future, which should able to run on well-known ones.

**Comment by palxex** [comment]
AppImage patch have been tested and merged. Please reopen if its not desired.
