### ISSUE TITLE
apk第二次进入闪退

### ISSUE THREAD

**Issue by luweitest** [sdlpal/sdlpal#175]
**Describe the bug / 描述问题**
从https://bintray.com/version/files/sdlpal/nightly/master/v2019-12-21-g47872da 下载的sdlpal-release.apk，第一次设置能进入，第二次就闪退，系统提示crash

**To Reproduce / 重现步骤**
1. 新建游戏，载入进度都一样
2. 删掉原app（不删无法覆盖安装），安装新apk
3. 正常进入，默认设置不改动，测试操作正常，退出
4. 再次打开，闪退，无任何显示和log记录
5. 清空数据可重新进入第3步

**Expected behavior期待的正确结果**
应正常打开

**Screenshots/Capture 截屏/录像**
无

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统:  Android 9
 - Device设备 Vivo Z5x
 - Version版本 v2019-12-21-g47872da
 - Resource游戏资源 DOS原版
 - Config配置 附件sdlpal.cfg
[sdlpal.cfg.log](https://github.com/sdlpal/sdlpal/files/4000267/sdlpal.cfg.log)
 - Verbose Log 详细日志文件 第一次进入将log选为verbose得到附件test.log。闪退无任何log。
[test.log](https://github.com/sdlpal/sdlpal/files/4000263/test.log)

**Additional context 其他上下文**
之前可用的老版本日期是2019-3-24

**Comment by luweitest** [comment]
顺便问下哪里可看到changelog，这样有时就不一定更新了

**Comment by palxex** [comment]
Please add regression test result; recent cfg change occurs at fac3226, please first test whether  https://bintray.com/sdlpal/nightly/master/v2019-12-20-g7f0aced have same problem, which just before the commit referred.

**Comment by luweitest** [comment]
> 
> Please add regression test result; recent cfg change occurs at [fac3226](https://github.com/sdlpal/sdlpal/commit/fac322608c7cc591ef9b50ad306fc2bc50ce6678), please first test whether https://bintray.com/sdlpal/nightly/master/v2019-12-20-g7f0aced have same problem, which just before the commit referred.

Yes, v2019-12-20-g7f0aced works good. And I should be more specific that in the reproduce step 3 above, "quit" should be "quit to setting". I re-tested that normal quit works in v2019-12-21-g47872da .

> A question: is the sdlpal.cfg you uploaded really copied from android? From the gamepath it seems a win32 one.

Yes. the sdlpal game resource directory is originally copied from a windows PC. So that means the file sdlpal.cfg is actually not used by the Android version. I deleted it and the app still works (or not works), without re-creating it.

> For changelog, you can see commit id from version string. For example v2019-12-21-g47872da means it refer to [47872da](https://github.com/sdlpal/sdlpal/commit/47872da2fb009c31178c9e882bb4197807c22d9a); you can then locate the commit in this repo, and see its commit message.

Source diff is not for layman like me. :)

**Comment by palxex** [comment]
https://github.com/sdlpal/sdlpal/commit/e20a20ab660a99db8bf3c95e56ff138c0091f333 should have fixed this problem, please test it.
Source diffing is not needed for seeing changes, just read the commit message on top of the page, which describes the intention of the specified commit. For example the mentioned commit is just for fixing the problem this issue referred to.

**Comment by luweitest** [comment]
On 2019-12-27 22:00, Pal Lockheart wrote:
> e20a20a 
> <https://github.com/sdlpal/sdlpal/commit/e20a20ab660a99db8bf3c95e56ff138c0091f333> 
> should have fixed this problem, please test it.

Yes, v2019-12-27-ge20a20a does not crash.

> Source diffing is not needed for seeing changes, just read the commit 
> message on top of the page, which describes the intention of the 
> specified commit. For example the mentioned commit is just for fixing 
> the problem this issue referred to.
> 
I see. Thanks!

-- 
Regards,
Lu Wei
IM:	xmpp:luweitest@riotcat.org
PGP:	0xA12FEF7592CCE1EA
