### ISSUE TITLE
PSP SDK gcc 4.9.3: ../libopusfile/celt/bands.c:570:1: 编译器内部错误：在 extract_insn 中，于 recog.c:2202

### ISSUE THREAD

**Issue by PalMusicFan** [sdlpal/sdlpal#176]
Please submit your issue in English or Chinese.
请使用中文或英文提交问题。

**Describe the bug / 描述问题**
请清晰明了地描述问题所在。
PSP SDK gcc 4.9.3 报告: ../libopusfile/celt/bands.c:570:1: 编译器内部错误：在 extract_insn 中，于 recog.c:2202

**To Reproduce / 重现步骤**
1. 使用附属的Makefile内容启动编译。

**Expected behavior期待的正确结果**
请清晰明了地描述期待的正确行为。
编译通过。

**Screenshots/Capture 截屏/录像**
如果可能，请提交截屏/录像来更直观地描述问题。
输出如下：
$ make
psp-gcc -I. -I/usr/local/pspdev/psp/sdk/include -O3 -G0 -Wall -g -I/usr/local/pspdev/psp/include/SDL -I../liboggvorbis/include -I../liboggvorbis/src -I../liboggvorbis/src/modes -I../liboggvorbis/src/books/coupled -I../liboggvorbis/src/books/floor -I../liboggvorbis/src/books/uncoupled -I../libopusfile/include -I../libopusfile/src -I../libopusfile/celt -I../libopusfile/silk -I../libopusfile/silk/float -DHAVE_CONFIG_H -DPSP=1 -std=gnu99 -D_GNU_SOURCE -D_PSP_FW_VERSION=371   -c -o ../libopusfile/celt/bands.o ../libopusfile/celt/bands.c
../libopusfile/celt/bands.c: 在函数‘spreading_decision’中:
../libopusfile/celt/bands.c:570:1: 错误：无法识别的指令：
 }
 ^
(insn 115 114 116 10 (set (reg:SI 325)
        (if_then_else:SI (ne:CC (reg:CC 67 $fcc0)
                (const_int 0 [0]))
            (reg:SI 232 [ tcount$0 ])
            (reg:SI 236 [ tcount$0 ]))) -1
     (nil))
../libopusfile/celt/bands.c:570:1: 编译器内部错误：在 extract_insn 中，于 recog.c:2202
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make: *** [<内置>：../libopusfile/celt/bands.o] 错误 1

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统:  Windows 10 1903 18362.535
$ help
GNU bash，版本 4.4.12(3)-release (x86_64-unknown-cygwin)
$ psp-gcc -v
使用内建 specs。
COLLECT_GCC=psp-gcc
COLLECT_LTO_WRAPPER=/usr/local/pspdev/libexec/gcc/psp/4.9.3/lto-wrapper.exe
目标：psp
配置为：../configure --prefix=/usr/local/pspdev --target=psp --enable-languages=c,c++ --enable-lto --with-newlib --with-gmp-include=/home/PC/psptoolchain/build/gcc-4.9.3/build-psp/gmp --with-gmp-lib=/home/PC/psptoolchain/build/gcc-4.9.3/build-psp/gmp/.libs --with-mpfr-include=/home/PC/psptoolchain/build/gcc-4.9.3/build-psp/../mpfr/src --with-mpfr-lib=/home/PC/psptoolchain/build/gcc-4.9.3/build-psp/mpfr/src/.libs --enable-cxx-flags=-G0
线程模型：single
gcc 版本 4.9.3 (GCC)

Makefile: 
TARGET = sdlpal

SOURCES  = . .. ../adplug \
../liboggvorbis/src ../liboggvorbis/src/modes ../liboggvorbis/src/books/coupled ../liboggvorbis/src/books/floor ../liboggvorbis/src/books/uncoupled \
../libopusfile/src ../libopusfile/celt ../libopusfile/silk ../libopusfile/silk/float
CFILES   = $(foreach dir, $(SOURCES), $(wildcard $(dir)/*.c))
CPPFILES = $(foreach dir, $(SOURCES), $(wildcard $(dir)/*.cpp))

OBJS = $(CFILES:.c=$(INTER).o) $(CPPFILES:.cpp=$(INTER).o)

PSPSDK = $(shell psp-config --pspsdk-path)

INCDIR = 
CFLAGS = -O3 -G0 -Wall -g -I/usr/local/pspdev/psp/include/SDL \
-I../liboggvorbis/include -I../liboggvorbis/src -I../liboggvorbis/src/modes \
-I../liboggvorbis/src/books/coupled -I../liboggvorbis/src/books/floor -I../liboggvorbis/src/books/uncoupled \
-I../libopusfile/include -I../libopusfile/src -I../libopusfile/celt -I../libopusfile/silk -I../libopusfile/silk/float \
 -DHAVE_CONFIG_H -DPSP=1 -std=gnu99 -D_GNU_SOURCE
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti -std=c++11 -I. -I../
ASFLAGS = $(CFLAGS)

LIBDIR =
LIBS = -L/usr/local/pspdev/psp/lib -lSDL -lm -lGL -lpspvfpu -L/usr/local/pspdev/psp/sdk/lib \
-lpspdebug -lpspgu -lpspctrl -lpspge -lpspdisplay -lpsphprm -lpspsdk -lpsprtc -lpspaudio -lpspmp3 -lc \
-lpspuser -lpsputility -lpspkernel -lpspnet_inet -lpspirkeyb -lpsppower \
 -lstdc++

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = SDLPal
#PSP_EBOOT_ICON = icon0.png
#PSP_EBOOT_PIC1 = PIC1.png

BUILD_PRX = 1
PSP_FW_VERSION = 371
#PSP_LARGE_MEMORY=1 

include $(PSPSDK)/lib/build.mak

**Additional context 其他上下文**
请在此追加觉得可能与此问题相关的任何细节。

**Comment by palxex** [comment]
Seems for compiler internal error, we've no idea but changing compiler.

**Comment by raptorsun** [comment]
把 psp/Makefile 里面CLAGS中的-O3 改成 -O2就行了。 psp-gcc 有bug.
把`CFLAGS = -O3 -G0 -Wall -g -I/usr/local/pspdev/psp/include/SDL \`
改成`CFLAGS = -O2 -G0 -Wall -g -I/usr/local/pspdev/psp/include/SDL \`

**Comment by PalMusicFan** [comment]
Thanks! CFLAGS = -O2 works! 
This version of Makefile:

TARGET = sdlpal

SOURCES  = . .. ../adplug \
../liboggvorbis/src ../liboggvorbis/src/modes ../liboggvorbis/src/books/coupled ../liboggvorbis/src/books/floor ../liboggvorbis/src/books/uncoupled \
../libopusfile/src ../libopusfile/celt ../libopusfile/silk ../libopusfile/silk/float
CFILES   = $(foreach dir, $(SOURCES), $(wildcard $(dir)/*.c))
CPPFILES = $(foreach dir, $(SOURCES), $(wildcard $(dir)/*.cpp))

OBJS = $(CFILES:.c=$(INTER).o) $(CPPFILES:.cpp=$(INTER).o)

PSPSDK = $(shell psp-config --pspsdk-path)

INCDIR = 
CFLAGS = -O2 -G0 -Wall -g -I/usr/local/pspdev/psp/include/SDL \
-I../liboggvorbis/include -I../liboggvorbis/src -I../liboggvorbis/src/modes \
-I../liboggvorbis/src/books/coupled -I../liboggvorbis/src/books/floor -I../liboggvorbis/src/books/uncoupled \
-I../liboggvorbis/include -I../libopusfile/include -I../libopusfile/src -I../libopusfile/celt -I../libopusfile/silk -I../libopusfile/silk/float \
 -DPSP=1 -std=gnu99 -D_GNU_SOURCE -DHAVE_CONFIG_H

CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti -std=c++11 -I. -I../
ASFLAGS = $(CFLAGS)

LIBDIR =
LIBS = -L/usr/local/pspdev/psp/lib -lSDL -lm -lGL -lpspvfpu -L/usr/local/pspdev/psp/sdk/lib \
-lpspdebug -lpspgu -lpspctrl -lpspge -lpspdisplay -lpsphprm -lpspsdk -lpsprtc -lpspaudio -lpspmp3 -lc \
-lpspuser -lpsputility -lpspkernel -lpspnet_inet -lpspirkeyb -lpsppower \
 -lstdc++

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = SDLPal
#PSP_EBOOT_ICON = icon0.png
#PSP_EBOOT_PIC1 = PIC1.png

BUILD_PRX = 1
PSP_FW_VERSION = 371
#PSP_LARGE_MEMORY=1 

include $(PSPSDK)/lib/build.mak
