### ISSUE TITLE
Android Latest Version Time Bar not Hidden

### ISSUE THREAD

**Issue by kinghtt** [sdlpal/sdlpal#178]
Hi Developer,

I found that in the recent android builds, the time and signal bar (which maybe called notification bar?) located at the top of the screen are not hidden, which made the game graphic area smaller and a little bit wired.
I remember that in the previous builds, the bar was hidden, which should be better for game experiences.
Could you please revert this change?
Thank you very much.

Best Regards,
Eric

**Comment by palxex** [comment]
Could you please test recent bintray builds, find the commit that introduces this change?

**Comment by kinghtt** [comment]
> Could you please test recent bintray builds, find the commit that introduces this change?

I tried the latest build, but seems the issue is still there. Could you please check? Thanks.

**Comment by palxex** [comment]
@kinghtt unfortunately I've no android environment now... and I saw no android styling change in commits of recent 2 year. 
Let's wait other developers.

**Comment by CecilHarvey** [comment]
Fixed
