### ISSUE TITLE
现在安卓版不是apk一体化吗

### ISSUE THREAD

**Issue by guotong1988** [sdlpal/sdlpal#179]
我看https://github.com/sdlpal/sdlpal/wiki
上写的需要玩家自己复制一些文件到手机内置存储，
谢谢！

**Comment by palxex** [comment]
sdlpal当前官方编译不含copyright assets，无法单独运行。请自行准备资源，比如在wiki中寻找大宇授权的免费资源，并按照wiki中的解说自行放置后配置运行。
issue不为讨论目的设立（仅接受bug报告，及feature请求），有需求请在gitter上提问。
如果仍有不明（比如wiki何处写得不够清楚）欢迎提出建议。
