### ISSUE TITLE
安卓java build失败

### ISSUE THREAD

**Issue by guotong1988** [sdlpal/sdlpal#181]
报错信息：
```
错误: 程序包org.libsdl.app不存在

错误: 找不到符号
符号: 类 SDLActivity
```
![image](https://user-images.githubusercontent.com/4702353/73043934-4d41bf80-3ea2-11ea-8fdf-0d63d5333bf2.png)

android studio 3.5.2 
win10

**Comment by guotong1988** [comment]
build.gradle
一律
compileSdkVersion 25

**Comment by guotong1988** [comment]
还是不行

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/73045175-d27ba300-3ea7-11ea-9bec-372fa9de6a4c.png)

**Comment by guotong1988** [comment]
搞不定
![image](https://user-images.githubusercontent.com/4702353/73058371-6c564680-3ece-11ea-9336-201e4be50244.png)

**Comment by PalMusicFan** [comment]
您是使用git来clone的git仓库吗？在clone过程中git是可以创建链接的状态吗？请注意，以下位置是个链接：sdlpal/android/app/src/main/java/org/libsdl/app 链接的目标是 sdlpal/3rd/SDL/android-project/app/src/main/java/org/libsdl/app

**Comment by guotong1988** [comment]
大概知道是个链接，没链上

**Comment by PalMusicFan** [comment]
那得链上，或者手工拷贝文件夹过去。后者以后git操作会有点问题。

**Comment by guotong1988** [comment]
SDL的就这些考过去就行了吧，还有其他没

**Comment by PalMusicFan** [comment]
你拷过去的话以后git操作会有点问题。
说真的还是建议用Win32测试。
