### ISSUE TITLE
请问编译不通过是为什么呢，The run destination My Mac is not valid for Running the scheme 'PalTests'.

### ISSUE THREAD

**Issue by mauersu** [sdlpal/sdlpal#187]
from:https://gitter.im/sdlpal/sdlpal 

> 运行请选用sdlpal scheme，paltests是单元测试。
> https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/BuildingYourApp.html
> choose scheme to build

**Comment by palxex** [comment]
。。。请在Scheme部分选中SDLPal再Run。或者看截图吧。
![截屏2020-08-09 下午1 19 14](https://user-images.githubusercontent.com/58222/89725539-151b5c00-da43-11ea-8e9b-85f65993f5fb.png)

**Comment by palxex** [comment]
讨论结束关闭，如需继续请重开。
