### ISSUE TITLE
Linux交叉编译win版本失败

### ISSUE THREAD

**Issue by Dachuan-Liu** [sdlpal/sdlpal#191]
Ubuntu 18.04.3 LTS，已安装minGW与SDL2
报错如下（省略部分编译信息），请问应该如何排除，谢谢！
#########################################################
$ make HOST=i686-w64-mingw32-
[LD] sdlpal.exe
/usr/bin/i686-w64-mingw32-ld: unrecognized option '--enable-new-dtags'
/usr/bin/i686-w64-mingw32-ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'sdlpal.exe' failed
make: *** [sdlpal.exe] Error 1

**Comment by palxex** [comment]
因为手头没有环境，在travis-ci上[尝试了一下](https://travis-ci.org/github/palxex/sdlpal/jobs/719607822)编译没有问题。看log他们的系统是Ubuntu 18.04.4 LTS。另外这个ld参数不是sdlpal引入的，应该是工具链的问题。请严格按照[.travis.yml里MinGW32 target的步骤](https://github.com/sdlpal/sdlpal/blob/master/.travis.yml#L34)设置环境，看看能否排除。

**Comment by Dachuan-Liu** [comment]
> 因为手头没有环境，在travis-ci上[尝试了一下](https://travis-ci.org/github/palxex/sdlpal/jobs/719607822)编译没有问题。看log他们的系统是Ubuntu 18.04.4 LTS。另外这个ld参数不是sdlpal引入的，应该是工具链的问题。请严格按照[.travis.yml里MinGW32 target的步骤](https://github.com/sdlpal/sdlpal/blob/master/.travis.yml#L34)设置环境，看看能否排除。

好的，我先试试，非常感谢～
