### ISSUE TITLE
Question about BLEP resampler

### ISSUE THREAD

**Issue by M-HT** [sdlpal/sdlpal#192]
In file `sdlpal.cfg.example` following is written:
```
# ResampleQuality: Indicates the resample quality, valid values from 0 to 4 (default).
#                  Larger value indicates higher quality and higher hardware requirement.
```
BLEP resampler (value 1) is slower than SINC resampler (value 4) - tested on ARM and X64 (both sse and non-sse versions).
I don't know the quality of the BLEP resampler, but if it's higher than SINC resampler, then the value of BLEP resampler should be higher than the value of SINC resampler.
And if the quality of the BLEP resampler is lower than SINC resampler, then BLEP resampler is unnecessary and can be removed.

What's the quality of BLEP resampler compared to SINC resampler and what action should be taken?

**Comment by palxex** [comment]
In fact the resamplers are directly took from fb2k adplug plugin. For maintainability we'd better not change the code.
Let's change the document. From [hydrogenaud wiki](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components_0.9/foo_dsp_multiresampler) we know in theory SINC should be better than BLEP. So just remove " and higher hardware requirement" should be enough.
