### ISSUE TITLE
Problem with SDL_OpenAudio in SDL1

### ISSUE THREAD

**Issue by M-HT** [sdlpal/sdlpal#193]
SDL function SDL_OpenAudio is called in file audio.c like [this](https://github.com/sdlpal/sdlpal/blob/0f0d45b6578300da4f01f7ac44ffb7e0c7da5419/audio.c#L262): `SDL_OpenAudio(&gAudioDevice.spec, &spec)`

When using SDL2, the function is [redefined](https://github.com/sdlpal/sdlpal/blob/0f0d45b6578300da4f01f7ac44ffb7e0c7da5419/audio.c#L66) as a call to SDL_OpenAudioDevice with the last parameter set to zero - that means that SDL_OpenAudioDevice is not allow to change `frequency`, `format`, `channels` or `samples`.
When using SDL1, these changes are allowed.

Allowing the changes when using SDL2 probably isn't the correct action, so the changes should be disabled when using SDL1 by setting the second parameter of SDL_OpenAudio to NULL - this disables all changes except for `samples`.
And since changing `samples` is allowed when using SDL1, maybe it can be allowed when using SDL2 ?

The [original code](https://github.com/sdlpal/sdlpal/blob/0f0d45b6578300da4f01f7ac44ffb7e0c7da5419/audio.c#L262):
```
   if (SDL_OpenAudio(&gAudioDevice.spec, &spec) < 0)
   {
      UTIL_LogOutput(LOGLEVEL_VERBOSE, "OpenAudio ERROR: %s, got spec:freq %d, format %d, channels %d, samples %d\n", SDL_GetError(), spec.freq, spec.format, spec.channels,  spec.samples);
      //
      // Failed
      //
      return -3;
   }
   else
   {
      UTIL_LogOutput(LOGLEVEL_VERBOSE, "OpenAudio succeed, got spec:freq %d, format %d, channels %d, samples %d\n", spec.freq, spec.format, spec.channels,  spec.samples);
      gAudioDevice.pSoundBuffer = malloc(gConfig.wAudioBufferSize * gConfig.iAudioChannels * sizeof(short));
   }
```
can be changed to:
```
#if SDL_VERSION_ATLEAST(2,0,0)
   #ifdef SDL_AUDIO_ALLOW_SAMPLES_CHANGE
   #define AUDIO_ALLOWED_CHANGES SDL_AUDIO_ALLOW_SAMPLES_CHANGE
   #else
   #define AUDIO_ALLOWED_CHANGES 0
   #endif
   gAudioDevice.id = SDL_OpenAudioDevice((gConfig.iAudioDevice >= 0 ? SDL_GetAudioDeviceName(gConfig.iAudioDevice, 0) : NULL), 0, &gAudioDevice.spec, &spec, AUDIO_ALLOWED_CHANGES);
   if (gAudioDevice.id == 0)
#else
   if (SDL_OpenAudio(&gAudioDevice.spec, NULL) < 0)
#endif
   {
#if SDL_VERSION_ATLEAST(2,0,0)
      UTIL_LogOutput(LOGLEVEL_VERBOSE, "OpenAudio ERROR: %s, got spec:freq %d, format %d, channels %d, samples %d\n", SDL_GetError(), spec.freq, spec.format, spec.channels,  spec.samples);
#else
      UTIL_LogOutput(LOGLEVEL_VERBOSE, "OpenAudio ERROR: %s\n", SDL_GetError());
#endif
      //
      // Failed
      //
      return -3;
   }
   else
   {
#if SDL_VERSION_ATLEAST(2,0,0)
      UTIL_LogOutput(LOGLEVEL_VERBOSE, "OpenAudio succeed, got spec:freq %d, format %d, channels %d, samples %d\n", spec.freq, spec.format, spec.channels,  spec.samples);
      gAudioDevice.spec.samples = spec.samples;
#else
      UTIL_LogOutput(LOGLEVEL_VERBOSE, "OpenAudio succeed, got spec:samples %d\n", gAudioDevice.spec.samples);
#endif
      gAudioDevice.pSoundBuffer = malloc(gAudioDevice.spec.samples * gConfig.iAudioChannels * sizeof(short));
   }
```

**Comment by palxex** [comment]
Forgot why the code was changed to not allowing, but in my memory in the beginning the SDL2 code was also allowing samplerate changing, until somebody found that in some situation ( which I failed to remember ) that allowing does not work. 
Do we have real scenarios that current code not works well, even when able to custom samplerate in cfg? If no, then I think we'd better just keep it to avoid regression happening.

**Comment by M-HT** [comment]
Everything works fine when using SDL2.

I encountered a problem with SDL_OpenAudio (using SDL1) when doing a port for [Pandora](https://en.wikipedia.org/wiki/Pandora_(console)) and [GP2X](https://en.wikipedia.org/wiki/GP2X). It was a while ago, so I don't remember the exact problem. All changes are in my fork of sdlpal - there are optimizations specific to these targets.

If you keep the original code, it probably won't be problem because most targets use SDL2.

**Comment by palxex** [comment]
OK, so seems at least the SDL2 part disabling freq changes does not introduce new problem. Let’s keep it for now.
