### ISSUE TITLE
针对 Apple Silicon 编译 SDLPal 的问题的集中讨论串

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#194]
这个问题使用公开聊天室的话、比较难以整理内容。就开了这个讨论串。
我的编译环境是 Intel mac mini 2018 与 macOS 11.0 Big Sur 还有 Xcode 12.2 版。
（手头没有 Apple Silicon mac 的市售机种，所以有些内容无法测试。但 Intel Mac 编译通二应用还是能做到的。）

第一个环节是编译 SDLPal 专用的 SDL Framework。
以前针对支持 Metal 的 macOS 10.11 SDK 编译的时候，好像必须搭配 GCC 来编译。
但这次 GCC 针对 macOS Big Sur 的新版本需要本地编译，听说要花四小时……
![image](https://user-images.githubusercontent.com/3164826/100108696-68100680-2eae-11eb-99be-223bc304f1aa.png)

……我就先用 LLVM 编译了，暂时编译成通二试试看。
```
xcodebuild -project SDL.xcodeproj -scheme Framework -configuration Release CONFIGURATION_BUILD_DIR="./" -arch x86_64 -arch arm64 only_active_arch=no -sdk macosx11.0 build && sudo rm -rf /Library/Frameworks/SDL2.framework && sudo mv -f SDL2.framework /Library/Frameworks/ && rm -rf ~/Library/Developer/Xcode/DerivedData/*
```
结果失败：
![image](https://user-images.githubusercontent.com/3164826/100108351-08196000-2eae-11eb-965e-f587e5072cf7.png)
然后我删掉了「-arch arm64 」之后，可以顺利编译 SDK Framework，但这样一来就仅支持 amd64 了、算不上通二。
其实用系统内建的现成的旧版 gcc 也可以编译，但其法编译 arm64：
![image](https://user-images.githubusercontent.com/3164826/100111163-27fe5300-2eb1-11eb-9981-c25fc1703f4c.png)

**Comment by palxex** [comment]
呃。不太了解为何需求target 10.11 sdk。big sur上xcode 12.2直接打开macos/pal.xcodeproj不做任何更改编译release即可获得universal2的sdlpal，sdl会作为依赖被编译出来并链接进去。以下是昨天为测试编译的包：https://bintray.com/sdlpal/nightly/download_file?file_path=SDLPal-m1testv2.7z ，经测试intel mac上运行正常，但m1 mac上目前唯一一份测试报告指出会报找不到文件（读写都不行，怀疑是arm macOS上加了新的类似沙箱的基础设施），但能跑到那里至少说明执行是成功的。

**Comment by ShikiSuen** [comment]
@palxex 所有在 Apple Silicon 机种的 mac 编译的二进位应用都得签名。
这个签名不一定非得是 Apple 年费研发者会员订阅资格才有的那种签名。
你随便用 keychain 签发一个证书来签名就行。

**Comment by ShikiSuen** [comment]
我有即时战斗需求，所以我必须自己重新编译。
另附新版 macOS 应用图示：[sdlpal.icns.zip](https://github.com/sdlpal/sdlpal/files/5590734/sdlpal.icns.zip)

**Comment by ShikiSuen** [comment]
(我主要是考慮到點開 xcode 再編譯的話會自動產生很多用不到的檔案、把 SDLPal 主源碼目錄弄髒。)

**Comment by ShikiSuen** [comment]
目前我这边用图形介面编译 SDL Framework 也是出现同样的错误：
![image](https://user-images.githubusercontent.com/3164826/100112698-e1115d00-2eb2-11eb-80e9-9d6e4a2275ec.png)

**Comment by palxex** [comment]
> @palxex 所有在 Apple Silicon 机种的 mac 编译的二进位应用都得签名。
> 这个签名不一定非得是 Apple 年费研发者会员订阅资格才有的那种签名。
> 你随便用 keychain 签发一个证书来签名就行。

xcode编译除非显式注明不要签名（像travis配置里ios那样）其实都会生成一个adhoc的签名，没有这个签名应该是连启动执行都不可能的。不过这个提醒了我，不是codesign的问题还可能是notarization的问题，之前看crossover第三方编译看到过类似情况，回头有时间折腾一下。

**Comment by ShikiSuen** [comment]
@palxex 我說的就是 notarization。
這個強制簽名就是為了方便系統監控得知「已經安裝到電腦內的應用有沒有被病毒等進行竄改」。

**Comment by ShikiSuen** [comment]
关于「OSAtomicCompareAndSwap32Barrier」，应该是在新的 SDK 当中被抛弃支持了。

**Comment by ShikiSuen** [comment]
![image](https://user-images.githubusercontent.com/3164826/100113717-f5a22500-2eb3-11eb-8cc4-7806bfd608f5.png)
我刪了這四行之後成功編譯。

**Comment by ShikiSuen** [comment]
在「SDL_spinlock.c」当中删除上述四行之后，下述命令可以正常编译 Framework：
```
export CXX=/usr/bin/clang && xcodebuild -project SDL.xcodeproj -scheme Framework -configuration Release CONFIGURATION_BUILD_DIR="./" -arch x86_64 -arch arm64 only_active_arch=no -sdk macosx10.11 build && sudo rm -rf /Library/Frameworks/SDL2.framework && sudo mv -f SDL2.framework /Library/Frameworks/ && rm -rf ~/Library/Developer/Xcode/DerivedData/*
```

**Comment by palxex** [comment]
> 目前我这边用图形介面编译 SDL Framework 也是出现同样的错误：
> ![image](https://user-images.githubusercontent.com/3164826/100112698-e1115d00-2eb2-11eb-80e9-9d6e4a2275ec.png)

这个在travis上也遇到了，但我本地无法触发，还在想怎么重现。解决了请务必在这里发一下方案。

> ![image](https://user-images.githubusercontent.com/3164826/100113717-f5a22500-2eb3-11eb-8cc4-7806bfd608f5.png)
> 我刪了這四行之後成功編譯。

。。。这个改法看起来是把锁语义变成了直接放行。这个地方我现在没条件看，但如果用的地方关键，引发条件竞争极易导致莫名其妙崩溃。建议看看新版sdl里是否有解决方案，没有的话给sdl提bug让他们解决去。

**Comment by ShikiSuen** [comment]
我發現只有 macOS 10.15 及更新的 macOS SDK 才能編譯通二應用。
你能編譯正常，估計是你設定了 macOS 10.11 的 SDK。
刪了上面這四行之後，我用下面的命令編譯的：
```
xcodebuild -project SDL.xcodeproj -scheme Framework -configuration Release CONFIGURATION_BUILD_DIR="./" -arch x86_64 -arch arm64 only_active_arch=no -sdk macosx10.15 build && sudo rm -rf /Library/Frameworks/SDL2.framework && sudo mv -f SDL2.framework /Library/Frameworks/ && rm -rf ~/Library/Developer/Xcode/DerivedData/*
```

**Comment by ShikiSuen** [comment]
紧接著，在此基础上，我用下述命令编译游戏本体成功：
```
xcodebuild -project Pal.xcodeproj -scheme SDLPal -configuration Release CONFIGURATION_BUILD_DIR="/Volumes/SDLPalDev/OUTPUT/MetalMac/" -arch x86_64 -arch arm64 only_active_arch=no -sdk macosx10.15 build && rm -rf /Users/shikisuen/Library/Developer/Xcode/DerivedData/*
```

**Comment by ShikiSuen** [comment]
欸我又搞錯了。上面兩條是正常編譯的，但只能正常編譯 x86_64。
ARM64 的編譯只能依賴 macOS 11 的 SDK（命令依舊是上面的兩條）。

**Comment by palxex** [comment]
> 我發現只有 macOS 10.15 及更新的 macOS SDK 才能編譯通二應用。
> 你能編譯正常，估計是你設定了 macOS 10.11 的 SDK。
> 刪了上面這四行之後，我用下面的命令編譯的：
> 
> ```
> xcodebuild -project SDL.xcodeproj -scheme Framework -configuration Release CONFIGURATION_BUILD_DIR="./" -arch x86_64 -arch arm64 only_active_arch=no -sdk macosx10.15 build && sudo rm -rf /Library/Frameworks/SDL2.framework && sudo mv -f SDL2.framework /Library/Frameworks/ && rm -rf ~/Library/Developer/Xcode/DerivedData/*
> ```

不去更改-sdk选项会自动选中当前xcode安装的最新sdk，xcode12.2上就是11.0。注意10.11是el captitan，11.0是big sur。

**Comment by ShikiSuen** [comment]
我以前故意用 El Capitan 的 SDK 来保证系统的向前相容性。
这次也想试试的，结果某些地方会撞墙失败。

看来，要想保证 SDLPal 对 ARM64 的相容性支持，那就必须得用至少 macOS 11.0 的 SDK。
但是源码库可以与 macOS 10.15 SDK 编译相容源码库共用。

**Comment by palxex** [comment]
> 我以前故意用 El Capitan 的 SDK 来保证系统的向前相容性。
> 这次也想试试的，结果某些地方会撞墙失败。
> 
> 看来，要想保证 SDLPal 对 ARM64 的相容性支持，那就必须得用至少 macOS 11.0 的 SDK。
> 但是源码库可以与 macOS 10.15 SDK 编译相容源码库共用。

其实不必担心这个，xcode配置里“使用哪个sdk”和“最低只允许在哪个版本下执行”是分开的。sdlpal目前后者仍指向10.9，要不是不允许我还想指向更低。虽然不能保证还能在mavericks上运行（没机器能用来测试了），但前天那个build（sdk同样是big sur）有人测试了mojave上可以正常工作。

**Comment by palxex** [comment]
> @palxex 所有在 Apple Silicon 机种的 mac 编译的二进位应用都得签名。
> 这个签名不一定非得是 Apple 年费研发者会员订阅资格才有的那种签名。
> 你随便用 keychain 签发一个证书来签名就行。

可以给出如何用keychain自行签发证书notarize的步骤吗？
参照[苹果的notarizing文档](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087734)直接用altool+免费开发者证书notarize-app，最后会返回The username ***@***.*** is not a member of the provider . Contact your team admin for assistance.

**Comment by ShikiSuen** [comment]
> > @palxex 所有在 Apple Silicon 机种的 mac 编译的二进位应用都得签名。
> > 这个签名不一定非得是 Apple 年费研发者会员订阅资格才有的那种签名。
> > 你随便用 keychain 签发一个证书来签名就行。
> 
> 可以给出如何用keychain自行签发证书notarize的步骤吗？
> 参照[苹果的notarizing文档](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087734)直接用altool+免费开发者证书notarize-app，最后会返回The username _**@**_.*** is not a member of the provider . Contact your team admin for assistance.

你直接这样试试看？：
「codesign -s - PAL.app」
但这样签名的话会导致这个应用只能在编译的电脑上运行。

**Comment by ShikiSuen** [comment]
https://stackoverflow.com/questions/62597785/code-signing-macos-application-without-apple-developer-account
看來蘋果稅是跑不了了。

**Comment by palxex** [comment]
spinlock在arm64 macOS SDK下的编译问题已解决，这个API已被deprecated但尚未取消，SDL少引用了一个头文件。

**Comment by palxex** [comment]
讨论涉及的问题已解决，有新情况再重开吧。
