### ISSUE TITLE
网页端游戏数据文件格式

### ISSUE THREAD

**Issue by baolintian** [sdlpal/sdlpal#197]
请问目前在浏览器运行的[模拟器](https://sdlpal.github.io/demo/sdlpal.html)加载的是什么格式数据，目前提示使用zip格式的压缩数据。
目前尝试了.rpg的压缩文件格式数据，但是运行均没有反应。
存档链接：
http://ys-h.ys168.com/45843/8382525/hwsgxVj3T446J4786GOKO0c/98saves.7z
http://ys-i.ys168.com/45857/7636994/jstkwTk3J55622X6K4OKObd/Pal51.7z

请问应该使用什么样的存档数据运行？能否提供相应的样例数据在网页端运行？谢谢~

**Comment by palxex** [comment]
需要整个游戏的zip包（注意：7z并未支持），98/dos均可。鉴于本项目的性质是引擎重写，不便提供资源，希望理解。
另外因为用来解压的jszip的一个未知bug，macOS finder打包的zip也无法支持，mac用户请用其他方法压缩，比如命令行。

**Comment by baolintian** [comment]
> 需要整个游戏的zip包（注意：7z并未支持），98/dos均可。鉴于本项目的性质是引擎重写，不便提供资源，希望理解。
> 另外因为用来解压的jszip的一个未知bug，macOS finder打包的zip也无法支持，mac用户请用其他方法压缩，比如命令行。

好的，非常感谢~

**Comment by palxex** [comment]
好的，那这个issue就关闭了。
此外提醒一下，此类讨论类内容以后可以发在discussion里，issue主要用来记录bug：）
