### ISSUE TITLE
ubuntu20.04运行错误

### ISSUE THREAD

**Issue by shouhuanxiaoji** [sdlpal/sdlpal#200]
Please submit your issue in English or Chinese.
在ubuntu20.04运行appimage文件后，弹出一个框，但是内容空白，也无法退出

**Describe the bug / 描述问题**
如上

**To Reproduce / 重现步骤**
1. 新建游戏
2.下载一个appimage格式的文件
3. 给与执行权限，然后双击运行
4. 弹出空白框，无法下一步，也无法关闭

**Expected behavior期待的正确结果**
希望能运行游戏

**Screenshots/Capture 截屏/录像**
![123](https://user-images.githubusercontent.com/4121607/106385755-dcb27480-640c-11eb-9a3f-d52139452d44.jpg)

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统: ubuntu 20.04 64位
 - Device设备 cpu:amd 2600x,显卡: amd rx580, 内存:32G
 - Version版本 下载了好几个appimage版本，包括最新版本
 - Resource游戏资源 仙剑98柔情版

 - Config配置 [upload your sdlpal.cfg here, or screenshot of config page on mobile versions 上传你的sdlpal.cfg，或者手机版配置页面的截图]
 终端没有内容输出

**Additional context 其他上下文**
请在此追加觉得可能与此问题相关的任何细节。

**Comment by palxex** [comment]
看起来是fltk显示出问题了。作为workaround请检查下你的~/.config下有没有生成sdlpal.cfg，没有的话用下列命令生成
```
cat << EOF > ~/.config/sdlpal.cfg
LogLevel=0
LogFileName=/home/你的用户名/sdlpal.log
GamePath=你的游戏资源路径
```
之后再运行一下试试。

**Comment by palxex** [comment]
经过征集测试，当前appimage的配置GUI（fltk）在以下两台上表现正常：
1. i5 4200H, GTX960M, ubuntu 20.04, Xorg GnomeShell
![fltk](https://user-images.githubusercontent.com/58222/106595470-95ec8800-658e-11eb-9cec-662a1ffdaf6d.png)

2. r5 3600, RX570, manjaro bleeding, Xorg Deepin和Plasma Wayland双环境均正常，下面是前者，后者忘记截了
![截图录屏_选择区域_20210202163655](https://user-images.githubusercontent.com/58222/106595515-a3097700-658e-11eb-9306-9f31e2484b35.png)

有可能的话请进一步提供信息帮助找到问题根源，谢谢。

**Comment by palxex** [comment]
因无反馈关闭，有新回复再开。
