### ISSUE TITLE
Android下图标有问题

### ISSUE THREAD

**Issue by lgq-lzw** [sdlpal/sdlpal#201]
Please submit your issue in English or Chinese.
Android(8.1/9.0)下图标有问题

**Describe the bug / 描述问题**
在Android(8.1/9.0)，440dp情况下，apk文件图标是一个白方块。安装完后，桌面图标正常，但在一些管理应用里头(如钛备份、幸运破解器、MIUI系统自带应用管理)里显示的PAL应用图标也是一个白方块。

建议中文环境里，应用名用中文，用英文PAL在一大堆应用里不好找。

建议自动判断资源目录里是否存在对应的mp3/ogg/mid文件，没有就不要列在下拉菜单里，或者文字提示资源不存在。新手不查资料还以为是apk自带资源。

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS操作系统:(MIUI 10/MIUI 11)
 - Device设备 红米6A/红米Note8
 - Version版本 2.0(1611768458)/v2021-01-27-gdbd2a4a

**Comment by palxex** [comment]
> 在Android(8.1/9.0)，440dp情况下，apk文件图标是一个白方块。安装完后，桌面图标正常，但在一些管理应用里头(如钛备份、幸运破解器、MIUI系统自带应用管理)里显示的PAL应用图标也是一个白方块。

对Android不是很熟悉，可以的话请直接给出PR吧。
 
> 建议中文环境里，应用名用中文，用英文PAL在一大堆应用里不好找。

据我所知，因为各种版权原因，这已经是若干次妥协后的结果了，再改动的可能不太乐观。

> 建议自动判断资源目录里是否存在对应的mp3/ogg/mid文件，没有就不要列在下拉菜单里，或者文字提示资源不存在。新手不查资料还以为是apk自带资源。

文字提示这个建议不错，先在android_toast分支中做了个简单实现。

**Comment by palxex** [comment]
因无反馈关闭。
