### ISSUE TITLE
UNIX compilled: Configuration menu doesn't appear after start-up, setting up English Language

### ISSUE THREAD

**Issue by Meresmata** [sdlpal/sdlpal#202]
After sdlpal is compiled for UNIX and running Ubuntu. Starting the sdlpal file, starts the game right away.
a Config file is create after quitting the game by pressing q and accepting 是.
When I add the line:
MessageFileName=m_eng.slf

to the config file to enable the English language (version 3.3)as described in readme.txt. The sdlpal crashes on startup.

1.  got a fresh pull from github
2.  installed sdl with https://gist.github.com/BoredBored/3187339a99f7786c25075d4d9c80fad5
3. created sdlpal via make

4. copied game to a folder: http://update1.baiyou100.com/resource/Pal98rqp.zip
5. copied the language pack (Version 3.3) into the same folder
6.  copied the sdlpal file into the folder
7. call : ./sdlpal (clicking does not work)

OS: Ubuntu 20.04 with Cinnamon
device: Tuxedo Pulse 14 (Laptop, AMD-CPU & GPU)

**Comment by palxex** [comment]
Sorry for the late reply, not sure why no notification mail received recently
For Linux users, please first try appimage nightly build, which could be found in bintray repo in readme. And ensure that using responding language file, for pal98rqp it’s under win_files.
If it still crash, please attach the cfg(for appimage it’s under ~/.config) and slf file here.

**Comment by palxex** [comment]
Closing due to lack of response.

**Comment by Meresmata** [comment]
Which of packages do I have to choose? None, of them locked as if correct. I found a lot of windows versions, some for consoles and a macos one?

**Comment by palxex** [comment]
If you’re using Linux, just choose AppImage. Download and chmod +x for it then run. Other Unix variant like *BSD needs to build for yourself.
Now nightly builds have moved to cloudsmith since bintray sunset, which could be find in readme, be sure choose build from master branch.

**Comment by Meresmata** [comment]
Thanks, did find the app image at first. Thanks. Works like charm.
