### ISSUE TITLE
要不要在使用说明里面写上 CD 音乐对应的档案名称的说明？

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#208]
目前 SDLPal 被大宇资讯官方用来上架 Steam 了。内含三个版本：
一、「DOS」：Dosbox 跑原版。
二、「PAL」：SDLPal 跑 DOS 版、不使用 AVI 过场动画。
三、「PAL98」：SDLPal 跑 Windows 95 / 98 版、使用 AVI 过场动画。

然而，有玩家在巴哈姆特反馈说 PAL98 版在所有需要读取 CD 音乐的地方都没有音乐。
我记不起来之前有没有问过 CD 音乐档案是怎样被 SDLPal 读取的。
刚刚看了 SDLPal 的 readme.md 发现里面也没有写。
索性在这里问一下好了。

**Comment by ShikiSuen** [comment]
原来在 wiki 里面……那我先关掉这个 issue 好了。
https://github.com/sdlpal/sdlpal/wiki/Settings_CHS

**Comment by ShikiSuen** [comment]
但我仍旧不知道原版 WIN95 版的 CD 的曲目清单顺序……

**Comment by palxex** [comment]
请参看https://github.com/palxex/palresearch/blob/master/PalScript/CDID.txt 。注意是十六进制，需要转换为十进制再+10000。
CD皆不响的问题，估计是cfg中CD设置不是none，没有成功fallback到music？可以发一份上来看看。
此外，steam版看截图提交较老，很多问题在新版中其实已经解决，但旧版中无能为力。
issue主要用于解决bug和新功能建议，不宜常开。此类讨论不妨发在discussion中。
