### ISSUE TITLE
针对同时阵亡的敌我人员数量 动态调整阵亡语音的音量

### ISSUE THREAD

**Issue by ShikiSuen** [sdlpal/sdlpal#209]
举例说林月如一鞭子抽死五个敌人的话，五个敌人同时惨叫的声音会变得非常响。
根据下图来看的话，可以看出来响度整整比击杀单个敌人要高出 7 分贝。
这在混音的角度来看已经是非常响了。

![image](https://user-images.githubusercontent.com/3164826/116119527-1edc1100-a6f1-11eb-8edf-4948950f77b7.png)

建议调整方案：

敌方同时死五人的话，每个人的战斗阵亡语音减去六分贝（多出一分贝稍微提升一下临场感）。
敌方同时死四人的话，每个人的战斗阵亡语音减去五分贝（多出一分贝稍微提升一下临场感）。
敌方或我方同时死三人的话，每个人的战斗阵亡语音减去 4.3 分贝（多出 0.5 分贝稍微提升一下临场感）。
敌方或我方同时死两人的话，每个人的战斗阵亡语音减去 0.5 分贝。

**Comment by palxex** [comment]
这个建议是很不错的，问题是……sdlpal目前的mixer（如果说有的话，其实个人感觉有点勉强）没有这么精确的调控手段。
推了个新分支，尝试对此类问题进行精确狙击：对多个连续的**同样的**音效，上一个播放完成前禁止下一个启动。
测试包在https://cloudsmith.io/~sdlpal/repos/sdlpal/packages/?q=tag%3Abranch%2Fdeny_sfx_repeating

**Comment by palxex** [comment]
因无反馈关闭，俟有需要重开。
