### ISSUE TITLE
能否支持一下圆梦版本的MOD

### ISSUE THREAD

**Issue by sunxuold** [sdlpal/sdlpal#218]
你好：

我这边针对圆梦1.1.1版本的MOD进行调试发现下面一些问题，但是仍然不能顺利进行游戏，目前已知并修复的问题：
1，整体是dos类型的数据，但是压缩却需要用YJ2_Decompress 方法
2，MAX_SCENES 的大小需要大于310
3，MAX_OBJECTS 需要大于675
4，MAX_INVENTORY应该是999
5，MAX_POISONS 应该是24
6，MAX_LEVELS 要大于2000
7，PLAYERROLES 结构是现有的2倍大小，也就是所有的WORD类型变量全部变为DWORD
8，ALLEXPERIENCE必现有的 多了两个 EXPERIENCE 类型变量不知道作用
这样游戏可以运行，但是物品不正常，战斗也不正常，不知道还需要怎么修改，能否处理一下？

**Comment by CecilHarvey** [comment]
第三方MOD请联系修改版作者获取源码.

**Comment by weimzh** [comment]
第三方SDLPAL MOD请联系修改版作者获取源码.
