### ISSUE TITLE
How to build sdlpal in arm mac without xcode?

### ISSUE THREAD

**Issue by gemini133** [sdlpal/sdlpal#225]
Doesnt want to install xcode which is too bloat for me...
and the xcodebuild right now requires xcode installed.
Is there other way to build xcode?
Thanks in advance

**Comment by weimzh** [comment]
I do not have macOS for now but maybe you can try build the *nix version
with libraries from homebrew?

**Comment by gemini133** [comment]
Thanks for pointing it out.

I mange to get it working.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/18028552/182010052-01f437aa-4617-479a-9b75-be3003dff4cf.png">

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/18028552/182010066-be0156fb-760d-4df9-a9cf-904865a79857.png">

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/18028552/182010068-c73cfb04-c01d-4c39-aaaf-e72b49ef69f6.png">

I don't know about c/c++ 
juw follow the compiler error and make the correction.
mostly they are about header file location, fix file one by one. (any setting to make the compiler more smart?)

**Comment by gemini133** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/18028552/182010126-82cd3851-a9f1-4c98-a6aa-c5596672d3d7.png">
