### ISSUE TITLE
击败金蟾鬼母后出现空的获取物品的提示

### ISSUE THREAD

**Issue by Hotege** [sdlpal/sdlpal#228]
请使用中文提交问题报告，将凡是非\*\*扩起来的部分替换为自己的描述。

**描述问题**
MacOS系统，使用Github Release的SDL2版本。在打败扬州城郊的金蟾鬼母后，会有获得物品的提示，但没有任何字在上面。

**重现步骤**
击败剧情中的金蟾鬼母后即可重现。具体战斗经过如下：
1. 林月如施放乾坤一掷，金蟾鬼母死亡
2. 李逍遥施放万剑诀
3. 蟾蜍发动普通攻击（普通攻击是否导致中毒不影响bug复现）
4. 林月如施放乾坤一掷，蟾蜍死亡，进入战斗结算阶段
经多次测试，上述bug均会出现。

**期待的正确结果**
击败蟾蜍应该得到一个傀儡虫，此时应有正确的文字提示。

**截屏/录像**
<img width="752" alt="截屏2022-08-17 19 37 02" src="https://user-images.githubusercontent.com/9608943/185110808-47510253-7785-493c-92c7-462e2c1080f4.png">

**环境（请完整提供如下信息）:**
 - 操作系统: macOS Monterey 12.4
 - 设备 MacBook Pro
 - 版本 https://github.com/sdlpal/sdlpal/releases/download/v2.0.2021.0214/sdlpal-macos.dmg 
 - 游戏资源 98柔情版（来自方块游戏平台）
 - 配置
<img width="191" alt="截屏2022-08-17 19 50 13" src="https://user-images.githubusercontent.com/9608943/185111543-1a640df8-95e1-4bd5-9941-3ff9be389ea0.png">
 - 详细日志文件 存档已被覆盖，无法获得日志

**其他上下文**
似乎其他战斗也会出现这种情况，这点需要得到证实。

**Comment by palxex** [comment]
已核实，该情况会在当前macOS的默认渲染后端metal下出现，触发条件是战后有任何掉落。
尚未定位问题所在，只能确定问题点位在text.c L1693行PAL_DialogWaitForKeyWithMaximumSeconds之前，确定字体已渲染至屏幕缓冲区，因未知原因在该渲染后端无法上屏。
临时解决方案是手动切换至OpenGL后端进行渲染，当前方法是在sdlpal.cfg中增加以下两句
```
EnableGLSL=1
Shader=plain.glsl
```
并下载[plain.glsl](../blob/master/shaders/plain.glsl) 至游戏资源目录（请务必以raw方式而不是html形式下载，确认方式是其前三个字节是#if）后运行。
