### ISSUE TITLE
Compiling issue under Windows

### ISSUE THREAD

**Issue by Nostaljaded** [sdlpal/sdlpal#23]
Compiling under Windows msys2 shell environment and getting this error:

$ make
[CC] ../adplug/fmopl.c
/bin/sh: sdl2-config: command not found
/bin/sh: gcc: command not found
make: *** [Makefile:38: ../adplug/fmopl.o] Error 127

'fmopl.o' file is missing in ../adplug/ directory
## 
**Steps:**
1. Followed the git instructions to clone sourcecode
2. In msys2 before compiling,
$ pacman -Syu
$ pacman -Su
$ pacman -S make
$ pacman -S mingw-w64-i686-SDL2
 
pacman SDL2 instructions courtesy of PalMusicFan

**Any ideas how to resolve it?**

Thanks.

P.S. Encounter a similar error in unix/linux with 'unix' folder
make: *** [../adplug/adlibemu.o] Error 127

**Comment by palxex** [comment]
Toolchain not installed?
`pacman -S mingw-w64-i686-toolchain`
If already installed but still cannot found, check the path and ensure /mingw32/bin is included, or directly force include it by
`export PATH=$PATH:/mingw32/bin`

**Comment by Nostaljaded** [comment]
Yup, those 2 are the required magic lines.
(Replacing `pacman -S mingw-w64-i686-toolchain` with this `pacman -S mingw-w64-i686-gcc` will reduce the download package size.)

Many thanks. :)
