### ISSUE TITLE
希望steam的仙剑支持ubuntu操作系统

### ISSUE THREAD

**Issue by ubuntu2204** [sdlpal/sdlpal#230]
希望steam的仙剑支持ubuntu22.04操作系统，我想在steam上买仙剑补票，但不太甘心使用proton进行游戏，希望steam上仙剑支持ubuntu22.04

![image](https://user-images.githubusercontent.com/44113641/202898117-42268812-e2ad-40a8-a12c-d3240323050d.png)

**Comment by weimzh** [comment]
steam版是开源的，源码在: 
https://github.com/aabby/sdlpal/tree/19f803ef4bc5297d378d79ada54886120f9d9289
可尝试自行编译、移植

也可以使用此处发布的原始代码配合steam的数据文件直接使用
