### ISSUE TITLE
iOS编译后，让去百游下载游戏文件

### ISSUE THREAD

**Issue by WuKongCoo1** [sdlpal/sdlpal#233]
请使用中文提交问题报告，将凡是非\*\*扩起来的部分替换为自己的描述。

**描述问题**
找不到下载地址

**重现步骤**
1. 是新建游戏还是载入进度（后者情况下请上传存档)
2. 如何操作
3. 出现了什么问题

**期待的正确结果**
能够给一个下载的链接

**Comment by weimzh** [comment]
请自行搜索，不要做伸手党
