### ISSUE TITLE
为啥限制了字号为15/16

### ISSUE THREAD

**Issue by RPG3D** [sdlpal/sdlpal#235]
原版画面马赛克严重，开了抗锯齿，但字体也被干扰了。
试图更换其他字体改善，但font.c:287 位置限制字号为15/16，在GitHub找了几个bdf字体都是32号的，无法使用。

**Comment by PalMusicFan** [comment]
原版仙剑画面是320x200分辨率的。SDLPal作为原版仙剑的移植版，画面也就是这个分辨率，包括文字都是绘制在这个分辨率的画面上。

因此，SDLPal的游戏内部全角文字其实只有最高16x16的单字符分辨率。至于加载15x15的BDF，那是利用了16x16空间的其中一部分。
