### ISSUE TITLE
Pressing 'Spacebar'/'Enter' key does not 'show all dialog lines at once'

### ISSUE THREAD

**Issue by Nostaljaded** [sdlpal/sdlpal#24]
As per subject heading.
It's noticeable and excruciatingly slow when using the ENG message file.

Works in PALDOS, PALWIN & SDLPAL (1.X) exes.

**Comment by louyihua** [comment]
Thank you for reporting the bug. This bug is fixed through PR #25. This issue will be closed once the PR is merged.
