### ISSUE TITLE
请问游戏运行速度可以设置调节么(变速)

### ISSUE THREAD

**Issue by DaBaiTuu** [sdlpal/sdlpal#241]
你好，由于我的平台是Linux，不像windows 能使用变速齿轮之类的软件，因此有此疑问/建议，由于我在 setting 等位置没有发现该 设置选项，亦未在文档中发祥相关资料，因此不知道是否可以调节，若能则请不吝赐教，若不能则可视为建议，谢谢

**Comment by wd22222222** [comment]
game.h 刷新速度
#define    FPS             10
#define    FRAME_TIME      (1000 / FPS)
battle.h 战斗速度
#define  BATTLE_FPS  ??

**Comment by DaBaiTuu** [comment]
> game.h 刷新速度 #define FPS 10 #define FRAME_TIME (1000 / FPS) battle.h 战斗速度 #define BATTLE_FPS ?
我按照你的提示试了一下，似乎是只加速了在地图上的移动速度，战斗速度的施法速度并没有提升，场景动画速度也是，不过还是非常感谢，还是希望能模拟变速齿轮的效果

**Comment by DaBaiTuu** [comment]
> game.h 刷新速度 #define FPS 10 #define FRAME_TIME (1000 / FPS) battle.h 战斗速度 #define BATTLE_FPS ??

我按照你的提示试了一下，似乎是只加速了在地图上的移动速度，战斗速度的施法速度并没有提升，场景动画速度也是，不过还是非常感谢，还是希望能模拟变速齿轮的效果

**Comment by wd22222222** [comment]
使用速度控制 达到变速器效果，是可以的，而且比较简单的方法是有的，程序中取系统时间的方法（函数）是SDL_GetTicks，如果将这个函数返回值加大或减小适当的倍数，可以实现变速效果。具体用什么办法实现就不说了，可以用宏，也可以用逐个替换方法。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sdlpal/sdlpal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月31日(星期天) 晚上6:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sdlpal/sdlpal] 请问游戏运行速度可以设置调节么(变速) (Issue #241)





  
game.h 刷新速度 #define FPS 10 #define FRAME_TIME (1000 / FPS) battle.h 战斗速度 #define BATTLE_FPS ?
 我按照你的提示试了一下，似乎是只加速了在地图上的移动速度，战斗速度的施法速度并没有提升，场景动画速度也是，不过还是非常感谢，还是希望能模拟变速齿轮的效果

**Comment by DaBaiTuu** [comment]
> 使用速度控制 达到变速器效果，是可以的，而且比较简单的方法是有的，程序中取系统时间的方法（函数）是SDL_GetTicks，如果将这个函数返回值加大或减小适当的倍数，可以实现变速效果。具体用什么办法实现就不说了，可以用宏，也可以用逐个替换方法。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sdlpal/sdlpal" ***@***.***&gt;; 发送时间:&nbsp;2023年12月31日(星期天) 晚上6:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [sdlpal/sdlpal] 请问游戏运行速度可以设置调节么(变速) (Issue #241) game.h 刷新速度 #define FPS 10 #define FRAME_TIME (1000 / FPS) battle.h 战斗速度 #define BATTLE_FPS ? 我按照你的提示试了一下，似乎是只加速了在地图上的移动速度，战斗速度的施法速度并没有提升，场景动画速度也是，不过还是非常感谢，还是希望能模拟变速齿轮的效果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢感谢，我是c语言小白，会根据你的方法自行学习的，issue 仍然 open 在这里，算是给开发组的建议了，留给开发组看一眼再close， 再次感谢

**Comment by palxex** [comment]
暂时没有这个功能的开发计划。需要的话请自行修改SDL_timer.c的SDL_GetTicks实现后重新编译SDL再与sdlpal链接即可。

**Comment by DaBaiTuu** [comment]
> 暂时没有这个功能的开发计划。需要的话请自行修改SDL_timer.c的SDL_GetTicks实现后重新编译SDL再与sdlpal链接即可。

好的谢谢
