### ISSUE TITLE
键盘快捷键失效，但是release下载的发版exe可使用/keyboard input invalid,but .exe file in release works （受到输入法影响）

### ISSUE THREAD

**Issue by DaBaiTuu** [sdlpal/sdlpal#242]
键盘快捷建如 w e a s，装备投掷，使用，围攻， 查看状态一开始是不起作用的

**重现步骤**
无论是是新建游戏还是载入进度都是一样
初始实验是在win10上

使用上下左右，没有问题，但是使用 w a s e等就会无效，当我尝试在我的 Linux 上 重现问题的时候，Linux上却直接弹出可输入法，这是我意识到是输入法影响了快捷键,因此在win10上关闭输入法即可，但是你们Release的编译好的程序则不会受到输入法影响，因此不知道是什么问题

**截屏/录像**
这里由于win10和ubuntu18.04 问题一致，只是win10不弹出输入法，因此给出ubuntu18.04 截图/视频

![Screenshot from 2023-12-17 19-37-48](https://github.com/sdlpal/sdlpal/assets/120782756/fe86a454-72de-48d3-843b-d937435dcccc)
![Screenshot from 2023-12-17 19-37-58](https://github.com/sdlpal/sdlpal/assets/120782756/40713f0e-1a1b-405e-9bf3-35538b2d9e70)

左侧为使用 Release 提供的 appimage（ubuntu下），右侧为自己编译（ubuntu，window10（vs2022 和msys ）编译下）问题一致
可见 其不受输入法影响，
视频：
[Screencast from 2023年12月17日 19时36分30秒.webm](https://github.com/sdlpal/sdlpal/assets/120782756/f52f1819-5ed0-4410-a548-6eb5585c61f4)

**环境（请完整提供如下信息）:**
 - 操作系统:  Windows 10 / ubuntu18.04
 - 游戏资源  尝试过不同资源 为梦幻梦时空3.75和98原版，问题也一样
 - 配置 （仅提供一份，2个资源仅路径不同）
 - KeepAspectRatio=1
FullScreen=0
LaunchSetting=0
Stereo=1
UseSurroundOPL=1
EnableKeyRepeat=0
UseTouchOverlay=0
EnableAviPlay=0
EnableGLSL=1
EnableHDR=0
SurroundOPLOffset=384
LogLevel=5
AudioDevice=-1
AudioBufferSize=1024
OPLSampleRate=49716
ResampleQuality=4
SampleRate=44100
MusicVolume=100
SoundVolume=100
WindowHeight=400
WindowWidth=640
TextureHeight=400
TextureWidth=640
CD=MP3
Music=MP3
MIDISynth=native
OPLCore=DBFLT
OPLChip=OPL2
GamePath=/home/dongsongb/SDLPAL_PROJECT/RealGames/mengshikong375
SavePath=/home/dongsongb/SDLPAL_PROJECT/RealGames/mengshikong375
ShaderPath=./

**Comment by palxex** [comment]
应该是因为最后的release编译还是用老的尚未支持IME的SDL版本编译的（我当时在mac下，没发现新增了这个问题，非常抱歉）。感谢反馈，但暂时没找到好的解决方案，先在SDL的编译配置里禁止了IME相关的处理以回到老的行为。

**Comment by DaBaiTuu** [comment]
> 先在SDL的编译配置里禁止了IME相关的处理以回到老的行为。

感谢您的回复，烦请不吝赐教 如何进行 ’在SDL的编译配置里禁止IME相关的处理‘   的操作

**Comment by palxex** [comment]
其实就是在sdl_config_windows.h里加了一行#define SDL_DISABLE_WINDOWS_IME 1。这一步已经完成了，自行编译时git pull后git submodule update将3rd/SDL更新到最近即可。另外，这个配置只对win32有影响，具体行为是同步到了linux版的行为，也就是开输入法会显示候选词让用户意识到输入法开了，想完全不受影响还是得手动关掉。如何恢复到完全不受输入法影响，目前我没有找到办法，等等其他人有没有解决方案吧。先把issue reopen了，昨天commit时写的fix不妥导致关闭了。

**Comment by palxex** [comment]
应已解决，对win版直接在imm层面禁止了ime处理（反正sdlpal也不需要）。回退了之前对sdl的hack。

**Comment by DaBaiTuu** [comment]
感谢！
