### ISSUE TITLE
内存泄露，

### ISSUE THREAD

**Issue by wd22222222** [sdlpal/sdlpal#244]
文件 script.c 2779,2874行
内存泄露，重复召唤，或分裂，覆盖原有精灵位置，造成内存泄露。
改进代码：

					//需要释放图像
					if (g_Battle.rgEnemy[i].lpSprite)
						free(g_Battle.rgEnemy[i].lpSprite);
					memset(&(g_Battle.rgEnemy[i]), 0, sizeof(BATTLEENEMY));

**Comment by palxex** [comment]
非常感谢，确认问题存在。
