### ISSUE TITLE
Spellpoint shadow box missing with DOS files + desc.dat & shadow box overlaps spell description with WIN files

### ISSUE THREAD

**Issue by Nostaljaded** [sdlpal/sdlpal#26]
Hi,

As per subject heading.

See picture.
![spboxshadow](https://cloud.githubusercontent.com/assets/28423237/25769942/d5518566-3259-11e7-990a-bb8705654a41.png)

[desc.dat](https://github.com/sdlpal/sdlpal/files/980686/desc.dat.txt) if required.

**Comment by louyihua** [comment]
Thank your for reporting this issue.
It is fixed through commit d46840a
