### ISSUE TITLE
戰鬥音樂不循環

### ISSUE THREAD

**Issue by EricChan1989** [sdlpal/sdlpal#272]
请使用中文提交问题报告，将凡是非\*\*扩起来的部分替换为自己的描述。

**描述问题**
戰鬥音樂播放完一遍後如果戰鬥未結束，音樂不會再次播放，整個戰鬥將只有音效。

**重现步骤**
任何戰鬥均可觸發，至少我使用midi作為音樂情況下可以。

**期待的正确结果**
戰鬥音樂可循環。

**截屏/录像**
無

**环境（请完整提供如下信息）:**
 - 操作系统: macos 14.3.1
 - 设备 macbook pro 16 inch 2023 m2 max
 - 版本 v2024-02-25-gfd934bb
 - 游戏资源 百游下载版
 - 配置
 - KeepAspectRatio=1
FullScreen=0
LaunchSetting=0
Stereo=1
UseSurroundOPL=1
EnableKeyRepeat=0
UseTouchOverlay=0
EnableAviPlay=1
EnableGLSL=0
EnableHDR=1
SurroundOPLOffset=384
LogLevel=5
AudioDevice=-1
AudioBufferSize=512
OPLSampleRate=49716
ResampleQuality=4
SampleRate=44100
MusicVolume=5
SoundVolume=100
WindowHeight=600
WindowWidth=960
TextureHeight=600
TextureWidth=960
CD=OGG
Music=MIDI
MIDISynth=native
OPLCore=DBFLT
OPLChip=OPL2
ScaleQuality=1

**Comment by EricChan1989** [comment]
不好意思再提一下，新修改好的mac版本midi循环逻辑和原版，包括sdlpal其他版本不同。mac版本音乐属于无缝循环，一个音乐放完了立即再来一遍。但是原版和其他平台版本都是有一个停顿的，一秒左右，听起来自然很多。望修正谢谢

**Comment by palxex** [comment]
抱歉，看了看限于实现这种精细调整做不到。native midi系列都是直接利用本地系统的midi合成能力，因此各平台特性都可能不同。有更精细调控需求的可以转用rix，或者换用尚在实验中的软midi合成器，后者应可保证各平台特性一致，但需要用户自备软波表文件。
以相对容易设置的tsf为例，涉及设置示例：（已下载sf2格式的波表并放置在资源文件夹，假设名为gs.sf2）
music=midi
midisynth=tinysoundfont
soundbank=gs.sf2
