### ISSUE TITLE
3ds运行游戏时，使用飞龙探云手不显示偷取到的金钱

### ISSUE THREAD

**Issue by Cope9560** [sdlpal/sdlpal#291]
物品偷到显示正常，金钱不显示，但是战斗结束后查看实际偷到了钱。

**Comment by PalMusicFan** [comment]
请问您用的是哪个版本？是编译好的吗？

**Comment by PalMusicFan** [comment]
您最近方便帮忙测试一下新版吗？

**Comment by PalMusicFan** [comment]
[3dssdlpal.zip](https://github.com/sdlpal/sdlpal/files/15369962/3dssdlpal.zip)

下载这个版本试试看。如果不能运行，请把屏幕显示贴上来，最好可以把您手里能运行的版本也打包贴上来。

**Comment by PalMusicFan** [comment]
麻烦您在这里直接贴zip包，方便归档。多谢多谢！
游戏资源本身不要贴，只贴3DS安装文件。

**Comment by PalMusicFan** [comment]
[sdlpal3ds72c185.zip](https://github.com/sdlpal/sdlpal/files/15387403/sdlpal3ds72c185.zip)
麻烦您再测试这个，看能不能运行。

**Comment by PalMusicFan** [comment]
好的，请问声音正常吗？还有速度？

战斗中是报错和播放音效有关吗？可以开新游戏测试，听李大娘敲李逍遥的那一声，如果报错请告诉我。

**Comment by PalMusicFan** [comment]
您看目前情况是不是这样：
1. 可以进游戏了，速度和音乐质量都可以。
2. 只要播放音效，就必然会报错。
3. 只要不播放音效，那么音乐正常，也可以比较正常地跑地图。

**Comment by PalMusicFan** [comment]
SoundVolume=0
尝试禁止音效播放，这样是否还出错？

**Comment by PalMusicFan** [comment]
好的，我会继续尝试。

**Comment by PalMusicFan** [comment]
麻烦您有空的时候测一下这个新版本：


[3dssdlpal0531.zip](https://github.com/user-attachments/files/15516000/3dssdlpal0531.zip)

**Comment by PalMusicFan** [comment]
这次请测试一下
1. OPLCore的其它几个选项是否可用
2. 新3DS高性能模式是否启用
3. 稳定性
4. 音质
5. 本issue提出的问题是否解决
此外这是测试版本，请勿转载。
