### ISSUE TITLE
在Mac上DOS版可以运行但是98版报错

### ISSUE THREAD

**Issue by caibengbu** [sdlpal/sdlpal#308]
开发者们好，非常感谢你们让在Mac上玩原生仙剑1成为可能！我下载了v2.0.2021.0214版本的[sdlpal-macos.dmg](https://github.com/sdlpal/sdlpal/releases/download/v2.0.2021.0214/sdlpal-macos.dmg)。并且从steam上下载了游戏内容。我把编译好的pal分别放到了圈起来的三个文件夹

<img width="685" alt="Screenshot 2024-10-29 at 21 55 02" src="https://github.com/user-attachments/assets/ec8996ef-a09f-47a2-8caa-f3fd4508076a">

PAL_DOS可以运行无问题。

<img width="638" alt="Screenshot 2024-10-29 at 21 59 08" src="https://github.com/user-attachments/assets/e801b185-73fd-48b0-9e7d-d6ebe4605aeb">

但是在PAL98和PAL里运行会给出如下错误

<img width="1021" alt="Screenshot 2024-10-29 at 21 57 17" src="https://github.com/user-attachments/assets/320e5ab3-7ea2-4e3f-a326-b9011c1c0ca4">

我的运行环境如下
 - 操作系统: MacOS Sequoia 15.1 (24B83)
 - 设备 MacBook Pro, 2022
 - 版本 v2.0.2021.0214
 - 游戏资源 Steam版
 - 配置 
<img width="203" alt="Screenshot 2024-10-29 at 22 02 45" src="https://github.com/user-attachments/assets/4113454f-66d0-482a-92db-3d2d69761093">

烦请各位看看，谢谢！

**Comment by palxex** [comment]
steam版似乎使用了新的本地化方案，sdlpal作为原版的重实现尚未支持。目前来说想运行98版，游戏资源请从[百游](http://pal5.aigame100.com/pal5/download/98xjrq.html)免费下载。
