### ISSUE TITLE
Multiple bugs when build with commit b78537e 

### ISSUE THREAD

**Issue by Nostaljaded** [sdlpal/sdlpal#33]
Hi,

Built with commit b78537e in MSYS2,
**1. No RIX music & sfx** (both PalWIN & PalDOS)

**2. Please restore the original title screen.** (PalWIN only)
![1](https://cloud.githubusercontent.com/assets/28423237/26230358/d8b85664-3c7a-11e7-9371-41ddeefdeebb.png)

**3. Fatal error on pressing '新的故事'** (PalWIN only)
![2](https://cloud.githubusercontent.com/assets/28423237/26230362/df009a72-3c7a-11e7-88c4-1fd20731facd.png)

All of them is working with 170509 commit 17f2b88.

Regards.

**Comment by palxex** [comment]
`git bisect` shows the problem introduced in 84832ae.

**Comment by louyihua** [comment]
@Nostaljaded
Thanks for your test. It's a wired bug as recent commit should not touch any code that may cause such bugs. And unfortunately, I've no way to reproduce this bug on my computer. 
However, as recent commits DO change the configuration part, so could you try to remove the current `sdlpal.cfg` from game directory, completely rebuilding the `sdlpal.exd` (by first do a `make clean`) and retry launching the game again to see whether the bug still remains?

**Comment by louyihua** [comment]
@palxex can you reproduce the bugs in your environment?

**Comment by palxex** [comment]
Yes, previous I made tests in macOS unix makefile and msys2, both verified the problems exist.

**Comment by Nostaljaded** [comment]
`make clean && make` fixes all the mentioned issues.

Thanks for resolving it.

**Bug:** Customized game message file support should not be limited to just 'msg' file extension.
![1](https://cloud.githubusercontent.com/assets/28423237/26271604/abb7c378-3d3a-11e7-9774-eb15852c6714.png)

**Comment by louyihua** [comment]
Here the extension is just a guidance, not a enforcement.
User can choose any file they want by just typing "*" in the input box.
However, what we want here is to pass a message that by default the message file SHOULD be ended with the `.msg` extension.

**Comment by palxex** [comment]
PR #34 verified and merged, in future just `make` should be enough, not need to `make clean` before.
@louyihua is it easy to add "*" to the drop-down menu as a secondary choise?

**Comment by louyihua** [comment]
Added in f38a6fc
