### ISSUE TITLE
cannot reload the savefile

### ISSUE THREAD

**Issue by Kitein** [sdlpal/sdlpal#36]
I used fedora 25 on my PC and I have tried sdlpal with an  original DOS-version of Pal1, I can run the game smoothly, but the problem is that  after I saved the game and then when I readed it ,it went to quit the game. I think I maybe have met a bug. what I should say is the number seemed much larger than normal in the save optionbar. after that I have tried  to run the game with dosbox, It ran all in the right way. that means I can save and load rightly.

**Comment by louyihua** [comment]
Could you please provide the version of SDLPal you use?

**Comment by Kitein** [comment]
I think it is the latest version what I have  downloaded from here.

**Comment by louyihua** [comment]
So you downloaded the pre-compiled version rather than compiling it yourself?

**Comment by Kitein** [comment]
I compiled myself , I mean I downloaded the original code and  compiled on my PC and did all the way as u wrote unter the code .

**Comment by Kitein** [comment]
and  the problem that showed in the terminal 
> Segmentation fault (core dumped) 
 when I tried to load the save file. the number on the saveslot1 is e.g. 4432 .

**Comment by louyihua** [comment]
Could you please provide your save file and the detailed steps that can re-produce the bug?

**Comment by Kitein** [comment]
1.> [@localhost-localdomainpal1dos]$ ./sdlpal
(then I run the  game smoothly)
then after the openscenes
2.I choose "新的开始" and click enter
3.after the dialogue with 李大娘 ，I press Esc move the cursor the "系统" click enter
4.then click "存储游戏" in the new menu  the cursor on the first saveslot "进度一"  I click enter
(now  I think  I have saved the game successfully) 
5.the I press Esc move the cursor to the "系统" and click enter 
6.the click "读取进度" in the new menu the cursor on the first saveslot "进度一" (now a number showed on the right side which is 7600), I click enter
7.the Terminal reported und showed the error as following and the same time the sdlpal game window quited

> Segmentation fault (core dumped)
the save file is here
[savefile.zip](https://github.com/sdlpal/sdlpal/files/1016195/savefile.zip)

thanks!

**Comment by louyihua** [comment]
Thank you for reporting this bug!
I've confirmed this bug and fixed it in a3d6b7e.

**Comment by Kitein** [comment]
I have tried again , u got it.  thanks a lot
