### ISSUE TITLE
macOS Sierra 10.12.5 xcode编译通过，运行出错

### ISSUE THREAD

**Issue by colmeluna** [sdlpal/sdlpal#46]
系统版本号：OS 10.12.5
Xcode:Version 8.3.2
库： SDL2 

编译没报错。
运行，出现错误 “FATAL ERROR:File not found:fbp.mkf!”

**Comment by colmeluna** [comment]
三方库放置位置为
/Library/Frameworks/SDL2.framework
/Library/Frameworks/SDL.framework

3ds制作cia报错 
$: make cia
fatal error: SDL.h: No such file or directory

**Comment by palxex** [comment]
Same env with you. Dont try directly run the debug app.
If you want debugging, try modify the working directory in scheme options to your game resources path, then click the run button.
If you want to get a standalone app, just archive it and find the app from orgnizer, then drag it to your game resource path and directly run it there.

**Comment by palxex** [comment]
For now SDLPal for macOS should use SDL2 in submodule, standalone framework not needed.
For 3DS questions, I don't have the environment, @nbzwt could you answer it? Thanks.

**Comment by colmeluna** [comment]
> Same env with you. Dont try directly run the debug app.
If you want debugging, try modify the working directory in scheme options to your game resources path, then click the run button.
If you want to get a standalone app, just archive it and find the app from orgnizer, then drag it to your game resource path and directly run it there.

好的，顺利解决。万分感谢！

**Comment by colmeluna** [comment]
> Same env with you. Dont try directly run the debug app.
If you want debugging, try modify the working directory in scheme options to your game resources path, then click the run button.
If you want to get a standalone app, just archive it and find the app from orgnizer, then drag it to your game resource path and directly run it there.

@palxex  好的问题解决！万分感谢！debug修改工作目录后直接运行通过 。

**Comment by louyihua** [comment]
问题已解决，关闭本issue
