### ISSUE TITLE
Freeing surface returned by SDL_SetVideoMode using SDL 1.2

### ISSUE THREAD

**Issue by M-HT** [sdlpal/sdlpal#48]
According to SDL 1.2 documentation on [SDL_SetVideoMode](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlsetvideomode.html), the surface returned by SDL_SetVideoMode should not be freed by the caller, but it is freed in functions VIDEO_Shutdown, VIDEO_Resize and VIDEO_ToggleFullscreen in file video.c.

**Comment by louyihua** [comment]
After some review, there is no such bug you reported.
