### ISSUE TITLE
Game crash on text overflow when using SDL 1.2

### ISSUE THREAD

**Issue by M-HT** [sdlpal/sdlpal#49]
When text overflows (which happens with the unofficial english translation) the game crashes with DivisionByZero in function SDL_SoftStretch.
The function SDL_SoftStretch (in SDL 1.2) crashes when the height or width of the source rectangle is zero.
This happens on text overflow in function VIDEO_UpdateScreen (in file video.c) on line:
`SDL_SoftStretch(gpScreen, (SDL_Rect *)lpRect, gpScreenReal, &dstrect);`

I fixed it by adding a check:
`if ((dstrect.w != 0) && (dstrect.h != 0)) SDL_SoftStretch(gpScreen, (SDL_Rect *)lpRect, gpScreenReal, &dstrect);`

(dstrect width and height is directly dependent on source rectangle width and height, so the check is valid)

**Comment by louyihua** [comment]
Thank you for your bug report.
If you have any solutions to this bug, please submit it through the pull request system so that we can check and merge it.
