### ISSUE TITLE
Native MIDI implementation for Linux using ALSA sequencer

### ISSUE THREAD

**Issue by M-HT** [sdlpal/sdlpal#50]
In the attachment is a native MIDI implementation for Linux (and only Linux) using [ALSA](https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture) sequencer.
[native_midi.zip](https://github.com/sdlpal/sdlpal/files/1133614/native_midi.zip)

Usable synth is detected automatically, but it can be overridden using MIDIUNIT environment variable.
It supports volume changes by adjusting the note velocity.
Add the parameter -lasound to LDFLAGS when compiling.

I played the whole game with it, so I'd say it's tested and works.

**Comment by louyihua** [comment]
Thank you for your suggestion.
But the issue tracking system here is only for report purpose. Please submit your code through as pull requests so that we can check and merge it if it is worth to do.
