### ISSUE TITLE
MIDI output using WildMIDI library

### ISSUE THREAD

**Issue by M-HT** [sdlpal/sdlpal#51]
In the attachment is an implementation of MIDI output using [WildMIDI](https://en.wikipedia.org/wiki/WildMIDI) library.
[midplay.zip](https://github.com/sdlpal/sdlpal/files/1133622/midplay.zip)

It uses the same interface as RIX, OGG, MP3 output.
It could be used by adding a new value to the Music configuration option or by adding a new configuration option which selects which MIDI output to use - this or native midi.
It was written against the release v2.0.2017.0523 and it's not adjusted to the latest code.

**Comment by louyihua** [comment]
Thank you for your suggestion.
But the issue tracking system here is only for report purpose. Please submit your code through as pull requests so that we can check and merge it if it is worth to do.
