### ISSUE TITLE
Can re-enable the thicker fonts in the DOS?

### ISSUE THREAD

**Issue by Nostaljaded** [sdlpal/sdlpal#52]
**Anyway to re-enable the thicker fonts in the DOS version?**
It's easier to read.
![thicker fonts](https://user-images.githubusercontent.com/28423237/28000336-b70389c0-6557-11e7-9554-3c2c1f2745a5.png)

Thanks for the AVI video playback support.

_Will there be another pre-release?_

**Comment by palxex** [comment]
Added back:) Please follow the tips in mentioned PR to enable it.
