### ISSUE TITLE
当铺bug

### ISSUE THREAD

**Issue by kinghtt1** [sdlpal/sdlpal#53]
最新build里，所有当铺都有两个bug（测试环境98柔情安卓）
1. 出售物品价格的那个框会和上方的物品列表框互相挡住并导致闪烁（如果觉得我描述不清楚，可以自己测试看一下，移动光标时很明显一直在那里闪）
2. 排在最后的一个物品被出售后光标不会自动移动到之前的一个物品上，而是直接消失，需要再次使用方向键移动光标才会再次出现
希望尽快修复，谢谢

**Comment by kinghtt1** [comment]
使用消耗性物品也有同样的问题。如果该消耗品是物品栏最后一个，且数量用到0以后光标将消失。建议更改逻辑，当某个物品的数量为0时，光标位置减一而不是当前的不变，如果光标位置小于第一个物品的位置，则其等于第一个物品的位置

**Comment by kinghtt1** [comment]
关于当铺售价栏位和物品栏互相挡住的问题建议可以把售价栏位位置下移，这样可以最小化的修改代码

**Comment by palxex** [comment]
感谢反馈，已改正。
