### ISSUE TITLE
物品列表说明文字bug

### ISSUE THREAD

**Issue by kinghtt1** [sdlpal/sdlpal#54]
当物品说明文字某一行长度达到32字节时（例如凤鸣刀的说明第一行等），第32个字节无法显示。也就是只能一排显示31字节。
但游戏中有多个道具的说明某一排会达到32字节。
理论上微调字符尺寸可以解决？
测试环境安卓98柔情

**Comment by kinghtt1** [comment]
仔细看了一下，小幅度将物品说明文字位置左移若干个像素应该可以更简单的解决问题

**Comment by palxex** [comment]
多谢指出，已在新版本中按98里的位置修正。
