### ISSUE TITLE
File Picker crash on LineageOS/CM

### ISSUE THREAD

**Issue by palxex** [sdlpal/sdlpal#57]
Test env: Oneplus ONE(bacon), CM14.1, Android 7.1.2
Everytime I clicked the "Browse" button it pops up a picker view( which content is empty ), then after 0.1s crash and exit.
Below is the logcat log during the crash:
[filepicker-crashlog.txt](https://github.com/sdlpal/sdlpal/files/1170878/filepicker-crashlog.txt)
CyanogenOS 13 Android 6.0.1 almost same.

**Comment by palxex** [comment]
Update: Verified the crash not happened on OnePlus 3T 7.0 and RedMi Note3 6.0. Seems maybe a LineageOS/CyanogenMOD specified problem.

**Comment by CecilHarvey** [comment]
Unfortunately LineageOS tends to cause overheat on Huawei Honor 4X, so maybe there is not much I can do on this :(

**Comment by palxex** [comment]
Still no luck:) remove it seems not change the crash. 
By this way, if I add toString next to the getText() in EXTRA_START_PATH line, at least the two file picker works. For the folder picker, now I can observe a blank tree, with a `..` link available for select; but once I clicked the `..`, crash again. Anyway 2/3 problems solved, is this patch suitable for your device?

**Comment by louyihua** [comment]
It seems the crash is caused by a UTF-8 error

**Comment by palxex** [comment]
Sure, can confirm only when crash happens the log contains the `string: 'intermediates.mid��'` lines.
But how code run there? In my tests I didn't start the game, just clicks in setting page. In this situation,  the midi file name should not even be passed to java, in my understand.

**Comment by CecilHarvey** [comment]
07-25 02:45:51.510 18680 18717 F art     : art/runtime/java_vm_ext.cc:470]   native: #09 pc 000c4d27  /system/lib/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+446)
07-25 02:45:51.510 18680 18717 F art     : art/runtime/java_vm_ext.cc:470]   native: #10 pc 000158b1  /system/lib/libopenjdk.so (Java_java_io_UnixFileSystem_list0+316)
07-25 02:45:51.510 18680 18717 F art     : art/runtime/java_vm_ext.cc:470]   native: #11 pc 0003dead  /data/dalvik-cache/arm/system@framework@boot.oat (Java_java_io_UnixFileSystem_list0__Ljava_io_File_2+96)

this happened when java.io.UnixFileSystem_list is called from Java code.
it's very likely that you have a file with an invalid filename on your sdcard.

**Comment by palxex** [comment]
Finally got it- -its a file in my /sdcard, which placed here when I debugging JNI code. Cannot delete it through ES explorer even, finally deleted via adb shell, and then the file picker works well.
A problem, though File Managers cannot process such file, at least they'll not crash- -
