### ISSUE TITLE
Little Suggestions on Positions of the desc and images in item interface

### ISSUE THREAD

**Issue by kinghtt1** [sdlpal/sdlpal#58]
Just refer to the previous comment of you guys, and had a carefully test, I just found that the positions like below are the most suitable ones, which are also seems the same as the original game.

Hopefully that the little changes below can be merged into your code, thank you.

line 3458 of script.c

		   int YBase = (wEventObjectID & PAL_ITEM_DESC_BOTTOM) ? 151 - gConfig.ScreenLayout.ExtraItemDescLines * 16 : 3;

line 232 of itemmenu.c
   + PAL_RLEBlitToSurface(bufImage, gpScreen, PAL_XY(8, 147 - iPictureYOffset));

**Comment by louyihua** [comment]
Thanks for your careful test. 
Since this is a small change, could you organize these changes into a commit and send it through the pull request system?

**Comment by palxex** [comment]
Applied the patch, makes it base + offset to avoid future recalculate. 
Agree with @louyihua, we'd better makes this kind of tweaks in PR in future.
