### ISSUE TITLE
Bug of Repeat Function in Battle Mode

### ISSUE THREAD

**Issue by kinghtt1** [sdlpal/sdlpal#62]
It is not a bug which can be seen every time inside the battle mode, and I only found it at the scenario as below.
When the team are inside SUOYAO TOWER, and Miss Zhao joined the team, and they dive into the bottom of the tower to destory the swords...
At that time, Miss Zhao is standing on the left side, Mr Li is in the middle, and Miss Lin is on the right.
When we use R key to repeat the magic skills of all the 3 guys used last roung, and if the MP of Miss Lin is not enough to use the magic skill, but Mr Li and Miss Zhao has enough MP to do so, only Miss Zhao can use the magic skill, and the other 2 will both use normal attack with their weapons.
I believe that the it will be that only Miss Lin to use the weapon attack, but the other 2 guys should use magic skills in the original game.
So could you please have a check?
The battle mode I tested was the classic one.
Thanks.

**Comment by kinghtt1** [comment]
let me explain this bug in another way.
There is a sequence of the team to take actions during a round, for example, the 1st one is Zhao, the 2nd one is Lin and the 3rd one is Li.
If anyone of the guys has no enough MP to use the magic skill, all the persons behind him/her will also use normal weapon attack instead of the magic skill he/she used last round.

**Comment by CecilHarvey** [comment]
Fixed, thanks
