### ISSUE TITLE
Can't save on Android

### ISSUE THREAD

**Issue by Chrisx333** [sdlpal/sdlpal#67]
Hello everyone!

I downloaded the sdlpal apk from the play store [https://play.google.com/store/apps/details?id=com.sdlpal.sdlpal ] and I can play [with the english patch], even I can load my previous saves from while I was playing on the pc, but the game won't let me save.

I used the 3 OPL emulators included with same luck.

Am I doing anything wrong?

Thanks for your time.

**Comment by palxex** [comment]
Hi, could you give a detail describe? Include your device model, OS version, root/xposed status, etc as more  detail as better. If above 6.0 please also show whether you've permitted the app storage accessing permission.
Then, please describe what happened when you try saving. Any warning pops? Or it silent fail? If you could, upload adb-logcat log once saving will greatly increase the possible to figure the problem.

**Comment by Chrisx333** [comment]
Wow, that was fast!
I'll try to reply to all your questions - even if I'm not very tech savvy.

My phone is a Xiaomi Remi 4a.
Android ver 6.0.1
I'm not rooted, and i don't know where I can give permission to the app for storage accessing.
When I try to save it "acts" as it was saved, but just doest do - no warnings or anything.

Ah!

I "fixed" it:
First I placed the folder on the sd - this is where I had the problem.
Then, I decided to place the archives on the default resource folder [/storage/emulated/0/sdlpal/]
and now I can save.

Maybe it was the "permission" thing?

Again, thank you for your time!

**Comment by palxex** [comment]
Glad to see you resolved it. Could you please do me a favor, help us figure what the actual problem? 
1, From spec I found redmi 4a has a internal storage, and also could insert a external sdcard. Do you means during when you cannot saving, you put the folder to the external sdcard, and then use the "browse" button navigating that folder and start gaming? 
2, By "place the archives on the default resource folder" do you mean move the folder to internal storage?
3, Did you ever seen a dialog that request "storage "(or something like it) permission during first time you open the app? If so, did you permit it?

**Comment by Chrisx333** [comment]
1 & 2 - Yes that's what I did.
At first I placed the folder with the archives on the SD card.
When you first run the app, there's a settings menu, and the very first option you have is the game's route for the folder. The default one is [/storage/emulated/0/sdlpal/], where the game's archives are now placed.

3. No. No pop-up, dialog, alert nor warning. No nothing.
Therefore, I didn't granted any permission because I wasn't asked for.
Also, I don't know if this matters, but I also use nes.emu and Snes9x and I can save on the SD, and I didn't need to give any special permission.

Hope this helps!

**Comment by palxex** [comment]
Thanks for your reply. So it seems MIUI's problem.
Android runtime permission that available since 6.0 will only pops up for apps that compiled target SDK 23 or later. Maybe the two emulators you tried were build for old android SDK, these version will not need permission granting for android 6+( but sometimes on android 7.0 this compatible mode has problem, that's why we changed target SDK ). Thanks very much for your detail reply:)
