### ISSUE TITLE
About Issue 68

### ISSUE THREAD

**Issue by kinghtt1** [sdlpal/sdlpal#69]
Hi There,

Just tested that after the change of issue 68, also win95 version cannot use a key pressing to make the "get item" box disappeared, but we just need to wait for about 2 seconds for it to disappear itself.
Previously, we can simply press a button to make it disappeared.
So does it able to make it a difference between win95 and Dos version? Or it will be very much inconvenience..

Thanks.

**Comment by palxex** [comment]
Thanks reporting. Verified exist both in DOS and Win95 version, seems I misunderstood original behavior.
With the referenced commit one can now press enter/space again to skip the dialog, while keeping the previous patch fixed behavior( keep pressing direction will not skip dialog immediately/ wait 1.4 sec dialog will disappear automatically ). 
But the original version could also skip the dialog by pressing any new direction keys, which cannot be archived in this patch, and I don't figured any way to archive both. Feel free to open PR on fixing it.

**Comment by CecilHarvey** [comment]
Fixed
