### ISSUE TITLE
portrait screen mode for Android version

### ISSUE THREAD

**Issue by kinghtt1** [sdlpal/sdlpal#71]
Hi There,

Just go back to the original version of sdlpal on google play, there is an option that we can run the game in portrait screen mode, which means that the upper half of the screen is the game, and the keypads at below.
 The benefit from this mode is that... the screen resolution is lower, so the quality of the graphic is higher.
 What's more, it is easier for many users to play and hold the mobile phone, or even with one hand only.
 After that, the whole game screen is not obstricted by the keypads.

Can you please make it in Android version?

Thanks.

**Comment by palxex** [comment]
Closing due to lack of discussing, logged in wiki, please reopen once needed.
