### ISSUE TITLE
敌人混乱状态后不会攻击队伍其他敌人

### ISSUE THREAD

**Issue by alex19861118** [sdlpal/sdlpal#73]
敌人混乱状态后不会攻击队伍其他敌人，而用DOSBOX运行PAL.EXE的话 敌人混乱后会攻击自己队伍里的其他人

**Comment by CecilHarvey** [comment]
原版很多情况混乱不一定会攻击其他人
具体条件未知

**Comment by flyher** [comment]
@alex19861118 
游戏就是这样的。。。混乱状态下会攻击队友，用药解，这个不是bug吧。

**Comment by palxex** [comment]
这个问题报的是敌人被我方下混乱状态，诸如阿奴法术里的鬼降，以及我方投掷物品鬼罂粟、幻蛊时的效果（受敌方巫抗影响，因此对大部分BOSS——巫抗10——无效）。印象中见过混乱后的敌人攻击其他敌人的情况（虽然更多的还是随机攻击我方），需要进一步总结原版行为。

**Comment by qyqqts** [comment]
原版混乱状态行为总结（PAL.exe测试98柔情篇，dosbox0.74测试梦幻2.2）：

我方队伍只有1人，中混乱后不攻击。

我方队伍有2人时，分AB两种情况测试，A：其中一人中混乱后可能会攻击另外一人也可能不攻击。B:两人都中混乱时可能出现3种情况：(1)两人都不攻击；(2)只有一人攻击己方；(3)两人互相攻击。

【借以上两种队伍状况判断，我方人物中混乱后，应该是随机从现有己方队伍中获取ID，如果ID是他人就攻击该人，如果ID是自己就不攻击】

我方队伍有3人时，每个人中混乱（试过任意1人、任意2人、全部3人中混乱的状态）的行动可能为3种：(1)不攻击；(2)攻击其他二人之一(3)攻击其他二人之二。

【所以上面的判断应该是正确】

敌方中混乱的时候行为模式较奇怪，0号位的敌人很特别，敌人位置标识如下图：
![360 20180613214318048](https://user-images.githubusercontent.com/39799800/41354957-e8ba7630-6f52-11e8-9c8b-41308a0684ff.jpg)

敌方队伍只有1人时，中混乱后不攻击。（此时该敌人是不是在0号位不重要）

敌方队伍有2-5人时分开分析，A：0号位有敌人，B：0号位没有敌人。

A：敌方队伍有2-5人且0号位有敌人时，根据敌方位置不同，中混乱后情况不同，0号位不攻击，1-4号位一定会攻击0号位（0号位是正常状态或者混乱状态都会被攻击），如0号位死亡（被我方打死或者被敌方的自己人打死都算），1-4号位仍处于混乱状态则会随机相互攻击或不攻击。

B：敌方队伍有2-4人且0号位没有敌人时，混乱的1-4号位则随机攻击其他号位的敌人或者不攻击。（其实就是和情况A的0号位敌人被打死后的情况一样）

【借此判断敌方0号位无敌人时，与上述我方混乱状态的情况一样】

另外假如怪会召唤，上述情况中的0号位重新被召唤出怪的时候，混乱的敌方还是只会且一定攻击0号位。

提点个人建议：觉得敌方这个混乱模式好二，测试总结的时候都觉得奇怪，觉得全部按照随机提取自己队伍中的ID来判断混乱后是攻击己方的哪个目标或者是不行动更合理点。

**Comment by CecilHarvey** [comment]
good job 👍

**Comment by alex19861118** [comment]
qyqqts 真是有心人

**Comment by ShikiSuen** [comment]
> 需要进一步总结原版行为。

如果这原版是DOS版的话，我问过姚仙了。他说：
「应该偶尔攻击自己伙伴，但不是每回合都会。」

**Comment by palxex** [comment]
已综合如上信息实现敌人混乱行为，请测试 [enemy_confuse](../tree/enemy_confuse) 分支。
当前实现行为为：随机攻击其友方（即我方之敌方），随机到自己则缄默。
同时对我方混乱进行了同样的处理，禁止了（与原版不符的）我方混乱、发动时仅剩一人转为随机攻击敌方（Alex报告）。

**Comment by palxex** [comment]
因一周内没有负面测试结果，已合并。关闭issue，有问题重开。
