### ISSUE TITLE
Do this project have midi working properly?

### ISSUE THREAD

**Issue by 799433746** [sdlpal/sdlpal#76]
I have installed wildmidi, along with timidity++, soundfont, but still get no BGM, The game is working properly though, is it a problem of my computer or BGM is not implemented yet. Mine is Manjaro 17.0. Thank you in advance.

**Comment by CecilHarvey** [comment]
Try:
make USE_ALSA=0

**Comment by palxex** [comment]
Just verified the current version works well with MIDI on manjaro.
This project uses native MIDI API on each platform. For Linux it's ALSA sequencer. 
For timidity:
Please first verify that your timidity is configured well, by able to plays MIDI file with `timidity filename` - the default installation don't contains configuration and will be total silent, you'd to do it manually, see https://wiki.archlinux.org/index.php/timidity.  Then start it in server mode(`timidity -iA`, or use the systemctl service included in the package). After both( and sdlpal.cfg Music=MIDI ) the MIDI playback in sdlpal should work. 
For wildmidi: I don't saw it support alsaseq mode, so it cannot be supported now. 
Other synthesizer that support alsaseq like fluidsynth should also works, please try them yourself.

**Comment by palxex** [comment]
Closing due to lack of response. If has further problem let's reopen it.
