### ISSUE TITLE
Fltk library

### ISSUE THREAD

**Issue by hsyysy** [sdlpal/sdlpal#8]
When I compile the source in Arch Linux, I find that the file in unix/unix.cpp use the fltk library
as <Fl/Fl.H> while the library in the system is FL/Fl.H. So the case is different. I create a symbolic
link in the unix directory as Fl -> /usr/include/FL to build the sdlpal without fault.

I don't know whether other distribution use the Fl. If it is only the Arch Linux, then it's a
small problem. But if it is a wider condition, you may change Fl to FL.

**Comment by palxex** [comment]
Our CI is building on ubuntu, just checked, seems ubuntu/debian's deb includes a symbolic link from Fl to FL. @louyihua how do you think about it?

**Comment by louyihua** [comment]
Checked the official document and it uses 'FL'.
So it seems that 'FL' is the standard way and 'Fl' may be a backward-compatibility thing.
I've changed the prefix from 'Fl' to 'FL' in d0e6fb7

**Comment by louyihua** [comment]
@hsyysy Thanks for your report.
I'll close the issue as the bug is fixed.
