### ISSUE TITLE
linux下无声

### ISSUE THREAD

**Issue by szh1123456** [sdlpal/sdlpal#85]
我编译后，放在98版本下，avi能播放，只是任何环境下都无声

**Comment by szh1123456** [comment]
配置我设置到了MIDI

**Comment by PalMusicFan** [comment]
请问您的Linux环境的具体信息是？
另外无声是无音乐无音效的完全无声，还是仅BGM无声有音效？AVI有声吗？RIX的BGM呢？

**Comment by PalMusicFan** [comment]
SDLPal对MIDI的支持依赖系统这边的MIDI合成器。而MIDI播放在Linux下也算是个麻烦事儿。

**Comment by palxex** [comment]
本讨论串因无反馈关闭。如欲重开，请提供上述信息。

**Comment by palxex** [comment]
用户在gitter提供了信息故重开，以下为用户提供的信息

> sdlpal.cfg:
> ```
> KeepAspectRatio=1
> FullScreen=0
> LaunchSetting=1
> Stereo=1
> UseSurroundOPL=1
> EnableKeyRepeat=0
> UseTouchOverlay=0
> EnableAviPlay=1
> SurroundOPLOffset=384
> LogLevel=5
> AudioDevice=-1
> AudioBufferSize=1024
> OPLSampleRate=49716
> ResampleQuality=4
> SampleRate=44100
> MusicVolume=100
> SoundVolume=100
> WindowHeight=400
> WindowWidth=640
> CD=OGG
> Music=RIX
> OPLCore=DBFLT
> OPLChip=OPL2
> AspectRatio=16:10
> ```
> 我换成了RIX还是无声，我chrome播放优酷视频等都有声音
> 系统发行版是Deepin

**Comment by palxex** [comment]
请尝试编译audio_diagnose分支
并将sdlpal.cfg的LogLevel改为0，新增LogFileName=diag.log
执行一次后，将游戏资源文件夹内的diag.log发上来。

**Comment by palxex** [comment]
本讨论串因无反馈再次关闭，相关代码已合并至主分支。
