### ISSUE TITLE
macOS下点击app报错bpf.mkf无法找到的fix.

### ISSUE THREAD

**Issue by sudormroot** [sdlpal/sdlpal#88]
在macOS下编译后，如果直接./Pal不会有错
但是点击app图标或者在别的路径执行Pal会报告错误。

错误的原因是通过"./"来访问资源文件的话如果Pal的工作路径不是Pal所在位置会导致无法定位。

解决方法是在main.c大约490行之后PAL_Init（）之前加入代码：
495 
496     //fix a bug on macOS
497 
498     char *work_path = strdup(argv[0]);
499 
500     int len = strlen(work_path);
501 
502 
503     while(--len) {
504         if(work_path[len] == '/') {
505             work_path[len] = '\0';
506             break;
507         }
508     }
509 
510     //printf("work_path=%s\n", work_path);
511 
512     chdir(work_path);
513 
514 
515    //
516    // Initialize everything
517    //
518    PAL_Init();

我预编译了一个版本：在我的（sudormroot）下的SDLPal-prebuild-macOS

**Comment by louyihua** [comment]
这个修改配置文件就可以了，不需要改代码
