### ISSUE TITLE
When will be a release available? 

### ISSUE THREAD

**Issue by skihyy** [sdlpal/sdlpal#9]
Hello, just want to know do you have a plan to have a release in executables in either Mac or Windows? Thanks.

**Comment by louyihua** [comment]
目前暂时没有确定的版本发布计划
不过当前的master分支版本基本没有什么大BUG，所以可以直接下载编译并使用

**Comment by skihyy** [comment]
这样 谢谢你。但是我从官网下载的exe导出来的包用编译以后的文件并不能运行 请问有什么解决办法吗？虽然说和这个issue没什么关系…

**Comment by louyihua** [comment]
现在有一个实验性的发布版了，如果有需要的话你可以试试。

**Comment by CecilHarvey** [comment]
https://github.com/sdlpal/sdlpal/releases
