### ISSUE TITLE
请问一下运行的时候出现 Invalid Instructions at 1fdd:(ffff - 5f4, 0, 0)这个问题怎么解决

### ISSUE THREAD

**Issue by qrzbing** [sdlpal/sdlpal#91]
我们的计算机组成原理课设要写一个小型操作系统（nemu），并在上面运行 x86 应用程序。其中某实验的结尾要求我们运行仙剑奇侠传。在编译成功之后，开始新的故事的时候，弹出对话框的动作会触发这个 ERROR。请问是不是我实现的指令集有问题？我一直找不到问题qwq
![pal_err4](https://user-images.githubusercontent.com/23500397/41104770-bf0fdf22-6a9e-11e8-869a-ad91fd242cc4.png)

**Comment by qrzbing** [comment]
由于我们在这一阶段还没有实现浮点数，因此暂时无法战斗，除此之外就只有对话会报错了，其他操作都没有问题。。

**Comment by louyihua** [comment]
SDLPal都进大学课堂了么？XD

请问你编译时用的源码版本是什么？

**Comment by louyihua** [comment]
@qrzbing 
从你截图的窗口背景来看，你们课上用的源码版本是较早以前的版本，也不知道你们的老师/助教是否曾对源代码进行了修改，故无法直接给出你这里报错的原因。
如果这个问题只是你个人遇到，而你的同学并未遇到的话，建议你先检查一下你所使用的那些.mkf文件和你同学处的是否一致；如果一致，则请你再检查一下你的编译参数与你同学处是否一致。

**Comment by qrzbing** [comment]
嗯。。编译参数是默认的，我没有修改过。。之前心态崩了，现在查找出来了，是之前实现 eflags 寄存器的时候一个函数实现的不对。。

**Comment by qrzbing** [comment]
https://github.com/NJU-ProjectN/ics-pa
https://legacy.gitbook.com/book/nju-ics/ics2017-programming-assignment/details
这个就是我们PA实验啦...虽然我不是南大的...不过这个感觉真的不错呢。。

**Comment by liangyifeng-nankai** [comment]
@qrzbing 同学问一下你是怎么解决的这个问题，我报错跟你一模一样，找不到哪里错了
