### ISSUE TITLE
关于重复上回合指令的目标错误问题

### ISSUE THREAD

**Issue by qyqqts** [sdlpal/sdlpal#92]
上传了一个视频:
https://v.youku.com/v_show/id_XMzY1NDMyNjEzMg==.html

就是召唤出新怪物后,R键重复指令攻击的目标发生了变化

**Comment by palxex** [comment]
为方便调错，以后此类问题请直接随描述上传存档，谢谢。

**Comment by qyqqts** [comment]
好的  我主要是怕我描述不清
[存档.zip](https://github.com/sdlpal/sdlpal/files/2086728/default.zip)
 
大概说下，通过R键重复之前的操作（单体伤害），当敌方正好又召唤了其他怪物时，会出现攻击目标变化，未攻击之前的怪。

**Comment by palxex** [comment]
已创建PR尝试解决此问题；以视频中的操作流程为例，能锁定对象了（在它死掉之前）。因为这个修复看起来比之前那个要广的多，请尽可能广泛的测试是否造成了战斗中关于动作对象的其他未预期改变。

**Comment by qyqqts** [comment]
好的 我测试一段时间再回复

**Comment by qyqqts** [comment]
已测试一段时间，正常走剧情，打过不同的敌人组合，暂未发现其他问题

只有一点，用的梦幻版灵葫咒这个东西在敌人血量低于25%时应该是百分百成功的，但发现有极低概率会失败，因为概率极低且似乎没有明显触发原因，所以无法有效控制来重现该问题，无法进行测试具体原因，但判断应该与R键重复操作无关

认为此依赖可以合并，此贴可以关闭

**Comment by palxex** [comment]
感谢测试~
